/**
 * Overview mock derived from Connexus Jira export (`/Users/musthafa/projects/drydock-ai/fixtures/jira/cnxs.csv`).
 * Regenerated by `scripts/generate-connexus-overview-mock.py`.
 *
 * Jira-backed: single Connexus team, sprints 34–37, completion, blocked,
 * spillover, burndown, delivery-trend proxy, Jira heatmap row, open bugs,
 * confidence score, overdue, fix versions, and Jira hygiene counts.
 * Still mocked: AI code risk, compliance, commits/PRs/deployments rows,
 * leadership approvals.
 */
export const CONNEXUS_OVERVIEW_DERIVED = {
  "lastSyncAt": "2026-09-09T16:48:00.000Z",
  "orgName": "Connexus",
  "projectKey": "CX",
  "defaultSprintId": "37",
  "teams": [
    {
      "key": "CONNEXUS",
      "name": "Connexus"
    }
  ],
  "sprints": [
    {
      "id": "37",
      "name": "Sprint 37",
      "startLabel": "Aug 27",
      "endLabel": "Sep 9",
      "rangeLabel": "Aug 27 \u2013 Sep 9, 2026",
      "start": "2026-08-27",
      "end": "2026-09-09"
    },
    {
      "id": "36",
      "name": "Sprint 36",
      "startLabel": "Aug 13",
      "endLabel": "Aug 26",
      "rangeLabel": "Aug 13 \u2013 Aug 26, 2026",
      "start": "2026-08-13",
      "end": "2026-08-26"
    },
    {
      "id": "35",
      "name": "Sprint 35",
      "startLabel": "Jul 30",
      "endLabel": "Aug 12",
      "rangeLabel": "Jul 30 \u2013 Aug 12, 2026",
      "start": "2026-07-30",
      "end": "2026-08-12"
    },
    {
      "id": "34",
      "name": "Sprint 34",
      "startLabel": "Jul 16",
      "endLabel": "Jul 29",
      "rangeLabel": "Jul 16 \u2013 Jul 29, 2026",
      "start": "2026-07-16",
      "end": "2026-07-29"
    }
  ],
  "base": {
    "score": 61,
    "band": "Caution",
    "caption": "Sprint 37 is at risk of delay",
    "completion": 67,
    "done": 79,
    "total": 118,
    "blocked": 0,
    "spillover": 0,
    "ai": 5,
    "comp": 2,
    "bugs": 224,
    "takeaways": [
      {
        "id": "blocked",
        "title": "0 items blocked",
        "subtitle": "Flat vs last sprint",
        "href": "/delivery-analysis?riskFocus=blockers",
        "tone": "success",
        "glyph": "\u2197"
      },
      {
        "id": "at-risk",
        "title": "0 items at risk",
        "subtitle": "Likely to spill over",
        "href": "/delivery-analysis?riskFocus=schedule#schedule-risk",
        "tone": "success",
        "glyph": "\u25f7"
      },
      {
        "id": "ai",
        "title": "AI code risk at 5%",
        "subtitle": "No high-risk areas",
        "href": "/code-analysis",
        "tone": "success",
        "glyph": "</>"
      },
      {
        "id": "compliance",
        "title": "2 compliance findings",
        "subtitle": "Mock \u2014 not in Jira export",
        "href": "/governance",
        "tone": "success",
        "glyph": "\u2662"
      }
    ],
    "pillars": [
      {
        "id": "delivery",
        "name": "Delivery",
        "score": 67,
        "delta": -33,
        "footnote": "79 / 118 completed",
        "progress": 67,
        "tone": "steady",
        "glyph": "\u2691",
        "href": "/delivery-analysis"
      },
      {
        "id": "code",
        "name": "Code",
        "score": 85,
        "delta": 0,
        "footnote": "0 blocked issues",
        "progress": 85,
        "tone": "steady",
        "glyph": "</>",
        "href": "/code-analysis"
      },
      {
        "id": "qa",
        "name": "QA",
        "score": 25,
        "delta": 0,
        "footnote": "224 open bugs",
        "progress": 25,
        "tone": "danger",
        "glyph": "\u2697",
        "href": "/qa"
      },
      {
        "id": "compliance",
        "name": "Compliance",
        "score": 81,
        "delta": 0,
        "footnote": "2 open findings",
        "progress": 81,
        "tone": "steady",
        "glyph": "\u2662",
        "href": "/governance"
      }
    ],
    "attention_count": 0,
    "attention_message": "Sprint 37 delivery signals look manageable \u2014 keep owners current.",
    "charts": {
      "deliveryTrend": {
        "rangeLabel": "Last 6 weeks",
        "target": 75,
        "points": [
          {
            "label": "Jul 29",
            "value": 53
          },
          {
            "label": "Aug 3",
            "value": 68
          },
          {
            "label": "Aug 7",
            "value": 33
          },
          {
            "label": "Aug 12",
            "value": 44
          },
          {
            "label": "Aug 17",
            "value": 53
          },
          {
            "label": "Aug 21",
            "value": 72
          },
          {
            "label": "Aug 26",
            "value": 78
          },
          {
            "label": "Aug 31",
            "value": 68
          },
          {
            "label": "Sep 4",
            "value": 71
          },
          {
            "label": "Sep 9",
            "value": 74
          }
        ]
      },
      "burndown": {
        "completed": 79,
        "total": 118,
        "ideal": [
          {
            "label": "Aug 27",
            "value": 118
          },
          {
            "label": "Aug 29",
            "value": 101
          },
          {
            "label": "Aug 31",
            "value": 84
          },
          {
            "label": "Sep 2",
            "value": 67
          },
          {
            "label": "Sep 3",
            "value": 51
          },
          {
            "label": "Sep 5",
            "value": 34
          },
          {
            "label": "Sep 7",
            "value": 17
          },
          {
            "label": "Sep 9",
            "value": 0
          }
        ],
        "actual": [
          {
            "label": "Aug 27",
            "value": 71
          },
          {
            "label": "Aug 29",
            "value": 70
          },
          {
            "label": "Aug 31",
            "value": 65
          },
          {
            "label": "Sep 2",
            "value": 56
          },
          {
            "label": "Sep 3",
            "value": 53
          },
          {
            "label": "Sep 5",
            "value": 50
          },
          {
            "label": "Sep 7",
            "value": 40
          },
          {
            "label": "Sep 9",
            "value": 39
          }
        ]
      },
      "heatmap": {
        "rangeLabel": "Last 2 weeks",
        "dayLabels": [
          "Aug 27",
          "Aug 28",
          "Aug 29",
          "Aug 30",
          "Aug 31",
          "Sep 1",
          "Sep 2",
          "Sep 3",
          "Sep 4",
          "Sep 5",
          "Sep 6",
          "Sep 7",
          "Sep 8",
          "Sep 9"
        ],
        "rows": [
          {
            "label": "Commits",
            "cells": [
              3,
              4,
              0,
              0,
              4,
              4,
              4,
              4,
              4,
              0,
              0,
              4,
              2,
              4
            ]
          },
          {
            "label": "PRs",
            "cells": [
              3,
              4,
              0,
              0,
              4,
              3,
              4,
              4,
              3,
              0,
              1,
              4,
              3,
              4
            ]
          },
          {
            "label": "Jira updates",
            "cells": [
              1,
              1,
              0,
              0,
              2,
              1,
              1,
              1,
              1,
              0,
              0,
              4,
              1,
              1
            ]
          },
          {
            "label": "Deployments",
            "cells": [
              2,
              0,
              0,
              1,
              0,
              0,
              3,
              0,
              0,
              1,
              0,
              0,
              2,
              0
            ]
          }
        ]
      }
    }
  },
  "byTeam": {
    "CONNEXUS": {
      "score": 61,
      "band": "Caution",
      "caption": "Sprint 37 is at risk of delay",
      "completion": 67,
      "done": 79,
      "total": 118,
      "blocked": 0,
      "spillover": 0,
      "ai": 5,
      "comp": 2,
      "bugs": 224,
      "takeaways": [
        {
          "id": "blocked",
          "title": "0 items blocked",
          "subtitle": "Flat vs last sprint",
          "href": "/delivery-analysis?riskFocus=blockers",
          "tone": "success",
          "glyph": "\u2197"
        },
        {
          "id": "at-risk",
          "title": "0 items at risk",
          "subtitle": "Likely to spill over",
          "href": "/delivery-analysis?riskFocus=schedule#schedule-risk",
          "tone": "success",
          "glyph": "\u25f7"
        },
        {
          "id": "ai",
          "title": "AI code risk at 5%",
          "subtitle": "No high-risk areas",
          "href": "/code-analysis",
          "tone": "success",
          "glyph": "</>"
        },
        {
          "id": "compliance",
          "title": "2 compliance findings",
          "subtitle": "Mock \u2014 not in Jira export",
          "href": "/governance",
          "tone": "success",
          "glyph": "\u2662"
        }
      ],
      "pillars": [
        {
          "id": "delivery",
          "name": "Delivery",
          "score": 67,
          "delta": -33,
          "footnote": "79 / 118 completed",
          "progress": 67,
          "tone": "steady",
          "glyph": "\u2691",
          "href": "/delivery-analysis"
        },
        {
          "id": "code",
          "name": "Code",
          "score": 85,
          "delta": 0,
          "footnote": "0 blocked issues",
          "progress": 85,
          "tone": "steady",
          "glyph": "</>",
          "href": "/code-analysis"
        },
        {
          "id": "qa",
          "name": "QA",
          "score": 25,
          "delta": 0,
          "footnote": "224 open bugs",
          "progress": 25,
          "tone": "danger",
          "glyph": "\u2697",
          "href": "/qa"
        },
        {
          "id": "compliance",
          "name": "Compliance",
          "score": 81,
          "delta": 0,
          "footnote": "2 open findings",
          "progress": 81,
          "tone": "steady",
          "glyph": "\u2662",
          "href": "/governance"
        }
      ],
      "attention_count": 0,
      "attention_message": "Sprint 37 delivery signals look manageable \u2014 keep owners current."
    }
  },
  "bySprint": {
    "36": {
      "kpis": {
        "score": 94,
        "band": "Strong",
        "caption": "Sprint 36 closed near plan",
        "completion": 100,
        "done": 11,
        "total": 11,
        "blocked": 0,
        "spillover": 0,
        "ai": 5,
        "comp": 2,
        "bugs": 224,
        "takeaways": [
          {
            "id": "blocked",
            "title": "0 items blocked",
            "subtitle": "Flat vs last sprint",
            "href": "/delivery-analysis?riskFocus=blockers",
            "tone": "success",
            "glyph": "\u2197"
          },
          {
            "id": "at-risk",
            "title": "0 items at risk",
            "subtitle": "Carried past Sprint 36",
            "href": "/delivery-analysis?riskFocus=schedule#schedule-risk",
            "tone": "success",
            "glyph": "\u25f7"
          },
          {
            "id": "ai",
            "title": "AI code risk at 5%",
            "subtitle": "No high-risk areas",
            "href": "/code-analysis",
            "tone": "success",
            "glyph": "</>"
          },
          {
            "id": "compliance",
            "title": "2 compliance findings",
            "subtitle": "Mock \u2014 not in Jira export",
            "href": "/governance",
            "tone": "success",
            "glyph": "\u2662"
          }
        ],
        "pillars": [
          {
            "id": "delivery",
            "name": "Delivery",
            "score": 100,
            "delta": 10,
            "footnote": "11 / 11 completed",
            "progress": 100,
            "tone": "steady",
            "glyph": "\u2691",
            "href": "/delivery-analysis"
          },
          {
            "id": "code",
            "name": "Code",
            "score": 85,
            "delta": 0,
            "footnote": "0 blocked issues",
            "progress": 85,
            "tone": "steady",
            "glyph": "</>",
            "href": "/code-analysis"
          },
          {
            "id": "qa",
            "name": "QA",
            "score": 25,
            "delta": 0,
            "footnote": "224 open bugs",
            "progress": 25,
            "tone": "danger",
            "glyph": "\u2697",
            "href": "/qa"
          },
          {
            "id": "compliance",
            "name": "Compliance",
            "score": 81,
            "delta": 0,
            "footnote": "2 open findings",
            "progress": 81,
            "tone": "steady",
            "glyph": "\u2662",
            "href": "/governance"
          }
        ],
        "attention_count": 0,
        "attention_message": "Sprint 36 delivery signals look manageable \u2014 keep owners current."
      },
      "charts": {
        "deliveryTrend": {
          "rangeLabel": "Last 6 weeks",
          "target": 75,
          "points": [
            {
              "label": "Jul 15",
              "value": 42
            },
            {
              "label": "Jul 20",
              "value": 54
            },
            {
              "label": "Jul 24",
              "value": 50
            },
            {
              "label": "Jul 29",
              "value": 53
            },
            {
              "label": "Aug 3",
              "value": 68
            },
            {
              "label": "Aug 7",
              "value": 33
            },
            {
              "label": "Aug 12",
              "value": 44
            },
            {
              "label": "Aug 17",
              "value": 53
            },
            {
              "label": "Aug 21",
              "value": 72
            },
            {
              "label": "Aug 26",
              "value": 88
            }
          ]
        },
        "burndown": {
          "completed": 11,
          "total": 11,
          "ideal": [
            {
              "label": "Aug 13",
              "value": 11
            },
            {
              "label": "Aug 15",
              "value": 9
            },
            {
              "label": "Aug 17",
              "value": 8
            },
            {
              "label": "Aug 19",
              "value": 6
            },
            {
              "label": "Aug 20",
              "value": 5
            },
            {
              "label": "Aug 22",
              "value": 3
            },
            {
              "label": "Aug 24",
              "value": 2
            },
            {
              "label": "Aug 26",
              "value": 0
            }
          ],
          "actual": [
            {
              "label": "Aug 13",
              "value": 0
            },
            {
              "label": "Aug 15",
              "value": 0
            },
            {
              "label": "Aug 17",
              "value": 0
            },
            {
              "label": "Aug 19",
              "value": 0
            },
            {
              "label": "Aug 20",
              "value": 0
            },
            {
              "label": "Aug 22",
              "value": 0
            },
            {
              "label": "Aug 24",
              "value": 0
            },
            {
              "label": "Aug 26",
              "value": 0
            }
          ]
        },
        "heatmap": {
          "rangeLabel": "Last 2 weeks",
          "dayLabels": [
            "Aug 13",
            "Aug 14",
            "Aug 15",
            "Aug 16",
            "Aug 17",
            "Aug 18",
            "Aug 19",
            "Aug 20",
            "Aug 21",
            "Aug 22",
            "Aug 23",
            "Aug 24",
            "Aug 25",
            "Aug 26"
          ],
          "rows": [
            {
              "label": "Commits",
              "cells": [
                2,
                4,
                0,
                0,
                3,
                4,
                4,
                4,
                4,
                0,
                0,
                3,
                1,
                0
              ]
            },
            {
              "label": "PRs",
              "cells": [
                3,
                4,
                0,
                0,
                3,
                4,
                4,
                4,
                4,
                0,
                1,
                1,
                0,
                0
              ]
            },
            {
              "label": "Jira updates",
              "cells": [
                1,
                2,
                0,
                0,
                1,
                3,
                4,
                1,
                3,
                0,
                0,
                1,
                0,
                0
              ]
            },
            {
              "label": "Deployments",
              "cells": [
                2,
                0,
                0,
                1,
                0,
                0,
                3,
                0,
                0,
                1,
                0,
                0,
                1,
                0
              ]
            }
          ]
        }
      }
    },
    "35": {
      "kpis": {
        "score": 83,
        "band": "Strong",
        "caption": "Sprint 35 closed near plan",
        "completion": 90,
        "done": 47,
        "total": 52,
        "blocked": 0,
        "spillover": 5,
        "ai": 5,
        "comp": 2,
        "bugs": 224,
        "takeaways": [
          {
            "id": "blocked",
            "title": "0 items blocked",
            "subtitle": "Flat vs last sprint",
            "href": "/delivery-analysis?riskFocus=blockers",
            "tone": "success",
            "glyph": "\u2197"
          },
          {
            "id": "at-risk",
            "title": "5 items at risk",
            "subtitle": "Carried past Sprint 35",
            "href": "/delivery-analysis?riskFocus=schedule#schedule-risk",
            "tone": "warning",
            "glyph": "\u25f7",
            "needsAction": true
          },
          {
            "id": "ai",
            "title": "AI code risk at 5%",
            "subtitle": "No high-risk areas",
            "href": "/code-analysis",
            "tone": "success",
            "glyph": "</>"
          },
          {
            "id": "compliance",
            "title": "2 compliance findings",
            "subtitle": "Mock \u2014 not in Jira export",
            "href": "/governance",
            "tone": "success",
            "glyph": "\u2662"
          }
        ],
        "pillars": [
          {
            "id": "delivery",
            "name": "Delivery",
            "score": 90,
            "delta": -10,
            "footnote": "47 / 52 completed",
            "progress": 90,
            "tone": "steady",
            "glyph": "\u2691",
            "href": "/delivery-analysis"
          },
          {
            "id": "code",
            "name": "Code",
            "score": 85,
            "delta": 0,
            "footnote": "0 blocked issues",
            "progress": 85,
            "tone": "steady",
            "glyph": "</>",
            "href": "/code-analysis"
          },
          {
            "id": "qa",
            "name": "QA",
            "score": 25,
            "delta": 0,
            "footnote": "224 open bugs",
            "progress": 25,
            "tone": "danger",
            "glyph": "\u2697",
            "href": "/qa"
          },
          {
            "id": "compliance",
            "name": "Compliance",
            "score": 81,
            "delta": 0,
            "footnote": "2 open findings",
            "progress": 81,
            "tone": "steady",
            "glyph": "\u2662",
            "href": "/governance"
          }
        ],
        "attention_count": 2,
        "attention_message": "5 items look likely to spill \u2014 review scope before close."
      },
      "charts": {
        "deliveryTrend": {
          "rangeLabel": "Last 6 weeks",
          "target": 75,
          "points": [
            {
              "label": "Jul 1",
              "value": 43
            },
            {
              "label": "Jul 6",
              "value": 66
            },
            {
              "label": "Jul 10",
              "value": 78
            },
            {
              "label": "Jul 15",
              "value": 42
            },
            {
              "label": "Jul 20",
              "value": 54
            },
            {
              "label": "Jul 24",
              "value": 50
            },
            {
              "label": "Jul 29",
              "value": 53
            },
            {
              "label": "Aug 3",
              "value": 68
            },
            {
              "label": "Aug 7",
              "value": 33
            },
            {
              "label": "Aug 12",
              "value": 65
            }
          ]
        },
        "burndown": {
          "completed": 47,
          "total": 52,
          "ideal": [
            {
              "label": "Jul 30",
              "value": 52
            },
            {
              "label": "Aug 1",
              "value": 45
            },
            {
              "label": "Aug 3",
              "value": 37
            },
            {
              "label": "Aug 5",
              "value": 30
            },
            {
              "label": "Aug 6",
              "value": 22
            },
            {
              "label": "Aug 8",
              "value": 15
            },
            {
              "label": "Aug 10",
              "value": 7
            },
            {
              "label": "Aug 12",
              "value": 0
            }
          ],
          "actual": [
            {
              "label": "Jul 30",
              "value": 5
            },
            {
              "label": "Aug 1",
              "value": 5
            },
            {
              "label": "Aug 3",
              "value": 5
            },
            {
              "label": "Aug 5",
              "value": 5
            },
            {
              "label": "Aug 6",
              "value": 5
            },
            {
              "label": "Aug 8",
              "value": 5
            },
            {
              "label": "Aug 10",
              "value": 5
            },
            {
              "label": "Aug 12",
              "value": 5
            }
          ]
        },
        "heatmap": {
          "rangeLabel": "Last 2 weeks",
          "dayLabels": [
            "Jul 30",
            "Jul 31",
            "Aug 1",
            "Aug 2",
            "Aug 3",
            "Aug 4",
            "Aug 5",
            "Aug 6",
            "Aug 7",
            "Aug 8",
            "Aug 9",
            "Aug 10",
            "Aug 11",
            "Aug 12"
          ],
          "rows": [
            {
              "label": "Commits",
              "cells": [
                1,
                4,
                0,
                0,
                4,
                3,
                1,
                2,
                4,
                0,
                0,
                4,
                4,
                4
              ]
            },
            {
              "label": "PRs",
              "cells": [
                2,
                4,
                0,
                0,
                4,
                1,
                1,
                3,
                1,
                0,
                1,
                4,
                4,
                4
              ]
            },
            {
              "label": "Jira updates",
              "cells": [
                1,
                3,
                0,
                0,
                2,
                1,
                1,
                1,
                1,
                0,
                0,
                4,
                3,
                4
              ]
            },
            {
              "label": "Deployments",
              "cells": [
                2,
                0,
                0,
                1,
                0,
                0,
                1,
                0,
                0,
                1,
                0,
                0,
                3,
                0
              ]
            }
          ]
        }
      }
    },
    "34": {
      "kpis": {
        "score": 94,
        "band": "Strong",
        "caption": "Sprint 34 closed near plan",
        "completion": 100,
        "done": 75,
        "total": 75,
        "blocked": 0,
        "spillover": 0,
        "ai": 5,
        "comp": 2,
        "bugs": 224,
        "takeaways": [
          {
            "id": "blocked",
            "title": "0 items blocked",
            "subtitle": "From flagged impediments and blockers",
            "href": "/delivery-analysis?riskFocus=blockers",
            "tone": "success",
            "glyph": "\u2197"
          },
          {
            "id": "at-risk",
            "title": "0 items at risk",
            "subtitle": "Carried past Sprint 34",
            "href": "/delivery-analysis?riskFocus=schedule#schedule-risk",
            "tone": "success",
            "glyph": "\u25f7"
          },
          {
            "id": "ai",
            "title": "AI code risk at 5%",
            "subtitle": "No high-risk areas",
            "href": "/code-analysis",
            "tone": "success",
            "glyph": "</>"
          },
          {
            "id": "compliance",
            "title": "2 compliance findings",
            "subtitle": "Mock \u2014 not in Jira export",
            "href": "/governance",
            "tone": "success",
            "glyph": "\u2662"
          }
        ],
        "pillars": [
          {
            "id": "delivery",
            "name": "Delivery",
            "score": 100,
            "delta": 0,
            "footnote": "75 / 75 completed",
            "progress": 100,
            "tone": "steady",
            "glyph": "\u2691",
            "href": "/delivery-analysis"
          },
          {
            "id": "code",
            "name": "Code",
            "score": 85,
            "delta": 0,
            "footnote": "0 blocked issues",
            "progress": 85,
            "tone": "steady",
            "glyph": "</>",
            "href": "/code-analysis"
          },
          {
            "id": "qa",
            "name": "QA",
            "score": 25,
            "delta": 0,
            "footnote": "224 open bugs",
            "progress": 25,
            "tone": "danger",
            "glyph": "\u2697",
            "href": "/qa"
          },
          {
            "id": "compliance",
            "name": "Compliance",
            "score": 81,
            "delta": 0,
            "footnote": "2 open findings",
            "progress": 81,
            "tone": "steady",
            "glyph": "\u2662",
            "href": "/governance"
          }
        ],
        "attention_count": 0,
        "attention_message": "Sprint 34 delivery signals look manageable \u2014 keep owners current."
      },
      "charts": {
        "deliveryTrend": {
          "rangeLabel": "Last 6 weeks",
          "target": 75,
          "points": [
            {
              "label": "Jun 17",
              "value": 76
            },
            {
              "label": "Jun 22",
              "value": 60
            },
            {
              "label": "Jun 26",
              "value": 55
            },
            {
              "label": "Jul 1",
              "value": 43
            },
            {
              "label": "Jul 6",
              "value": 66
            },
            {
              "label": "Jul 10",
              "value": 78
            },
            {
              "label": "Jul 15",
              "value": 42
            },
            {
              "label": "Jul 20",
              "value": 54
            },
            {
              "label": "Jul 24",
              "value": 50
            },
            {
              "label": "Jul 29",
              "value": 74
            }
          ]
        },
        "burndown": {
          "completed": 75,
          "total": 75,
          "ideal": [
            {
              "label": "Jul 16",
              "value": 75
            },
            {
              "label": "Jul 18",
              "value": 64
            },
            {
              "label": "Jul 20",
              "value": 54
            },
            {
              "label": "Jul 22",
              "value": 43
            },
            {
              "label": "Jul 23",
              "value": 32
            },
            {
              "label": "Jul 25",
              "value": 21
            },
            {
              "label": "Jul 27",
              "value": 11
            },
            {
              "label": "Jul 29",
              "value": 0
            }
          ],
          "actual": [
            {
              "label": "Jul 16",
              "value": 0
            },
            {
              "label": "Jul 18",
              "value": 0
            },
            {
              "label": "Jul 20",
              "value": 0
            },
            {
              "label": "Jul 22",
              "value": 0
            },
            {
              "label": "Jul 23",
              "value": 0
            },
            {
              "label": "Jul 25",
              "value": 0
            },
            {
              "label": "Jul 27",
              "value": 0
            },
            {
              "label": "Jul 29",
              "value": 0
            }
          ]
        },
        "heatmap": {
          "rangeLabel": "Last 2 weeks",
          "dayLabels": [
            "Jul 16",
            "Jul 17",
            "Jul 18",
            "Jul 19",
            "Jul 20",
            "Jul 21",
            "Jul 22",
            "Jul 23",
            "Jul 24",
            "Jul 25",
            "Jul 26",
            "Jul 27",
            "Jul 28",
            "Jul 29"
          ],
          "rows": [
            {
              "label": "Commits",
              "cells": [
                2,
                3,
                0,
                0,
                3,
                4,
                0,
                4,
                4,
                0,
                0,
                4,
                1,
                2
              ]
            },
            {
              "label": "PRs",
              "cells": [
                3,
                3,
                0,
                0,
                3,
                3,
                1,
                4,
                4,
                0,
                1,
                1,
                2,
                3
              ]
            },
            {
              "label": "Jira updates",
              "cells": [
                2,
                2,
                0,
                0,
                1,
                3,
                1,
                4,
                4,
                0,
                0,
                1,
                1,
                1
              ]
            },
            {
              "label": "Deployments",
              "cells": [
                2,
                0,
                0,
                1,
                0,
                0,
                1,
                0,
                0,
                1,
                0,
                0,
                2,
                0
              ]
            }
          ]
        }
      }
    }
  },
  "byTeamSprint": {
    "CONNEXUS:36": {
      "score": 94,
      "band": "Strong",
      "caption": "Sprint 36 closed near plan",
      "completion": 100,
      "done": 11,
      "total": 11,
      "blocked": 0,
      "spillover": 0,
      "ai": 5,
      "comp": 2,
      "bugs": 224,
      "takeaways": [
        {
          "id": "blocked",
          "title": "0 items blocked",
          "subtitle": "Flat vs last sprint",
          "href": "/delivery-analysis?riskFocus=blockers",
          "tone": "success",
          "glyph": "\u2197"
        },
        {
          "id": "at-risk",
          "title": "0 items at risk",
          "subtitle": "Carried past Sprint 36",
          "href": "/delivery-analysis?riskFocus=schedule#schedule-risk",
          "tone": "success",
          "glyph": "\u25f7"
        },
        {
          "id": "ai",
          "title": "AI code risk at 5%",
          "subtitle": "No high-risk areas",
          "href": "/code-analysis",
          "tone": "success",
          "glyph": "</>"
        },
        {
          "id": "compliance",
          "title": "2 compliance findings",
          "subtitle": "Mock \u2014 not in Jira export",
          "href": "/governance",
          "tone": "success",
          "glyph": "\u2662"
        }
      ],
      "pillars": [
        {
          "id": "delivery",
          "name": "Delivery",
          "score": 100,
          "delta": 10,
          "footnote": "11 / 11 completed",
          "progress": 100,
          "tone": "steady",
          "glyph": "\u2691",
          "href": "/delivery-analysis"
        },
        {
          "id": "code",
          "name": "Code",
          "score": 85,
          "delta": 0,
          "footnote": "0 blocked issues",
          "progress": 85,
          "tone": "steady",
          "glyph": "</>",
          "href": "/code-analysis"
        },
        {
          "id": "qa",
          "name": "QA",
          "score": 25,
          "delta": 0,
          "footnote": "224 open bugs",
          "progress": 25,
          "tone": "danger",
          "glyph": "\u2697",
          "href": "/qa"
        },
        {
          "id": "compliance",
          "name": "Compliance",
          "score": 81,
          "delta": 0,
          "footnote": "2 open findings",
          "progress": 81,
          "tone": "steady",
          "glyph": "\u2662",
          "href": "/governance"
        }
      ],
      "attention_count": 0,
      "attention_message": "Sprint 36 delivery signals look manageable \u2014 keep owners current."
    },
    "CONNEXUS:35": {
      "score": 83,
      "band": "Strong",
      "caption": "Sprint 35 closed near plan",
      "completion": 90,
      "done": 47,
      "total": 52,
      "blocked": 0,
      "spillover": 5,
      "ai": 5,
      "comp": 2,
      "bugs": 224,
      "takeaways": [
        {
          "id": "blocked",
          "title": "0 items blocked",
          "subtitle": "Flat vs last sprint",
          "href": "/delivery-analysis?riskFocus=blockers",
          "tone": "success",
          "glyph": "\u2197"
        },
        {
          "id": "at-risk",
          "title": "5 items at risk",
          "subtitle": "Carried past Sprint 35",
          "href": "/delivery-analysis?riskFocus=schedule#schedule-risk",
          "tone": "warning",
          "glyph": "\u25f7",
          "needsAction": true
        },
        {
          "id": "ai",
          "title": "AI code risk at 5%",
          "subtitle": "No high-risk areas",
          "href": "/code-analysis",
          "tone": "success",
          "glyph": "</>"
        },
        {
          "id": "compliance",
          "title": "2 compliance findings",
          "subtitle": "Mock \u2014 not in Jira export",
          "href": "/governance",
          "tone": "success",
          "glyph": "\u2662"
        }
      ],
      "pillars": [
        {
          "id": "delivery",
          "name": "Delivery",
          "score": 90,
          "delta": -10,
          "footnote": "47 / 52 completed",
          "progress": 90,
          "tone": "steady",
          "glyph": "\u2691",
          "href": "/delivery-analysis"
        },
        {
          "id": "code",
          "name": "Code",
          "score": 85,
          "delta": 0,
          "footnote": "0 blocked issues",
          "progress": 85,
          "tone": "steady",
          "glyph": "</>",
          "href": "/code-analysis"
        },
        {
          "id": "qa",
          "name": "QA",
          "score": 25,
          "delta": 0,
          "footnote": "224 open bugs",
          "progress": 25,
          "tone": "danger",
          "glyph": "\u2697",
          "href": "/qa"
        },
        {
          "id": "compliance",
          "name": "Compliance",
          "score": 81,
          "delta": 0,
          "footnote": "2 open findings",
          "progress": 81,
          "tone": "steady",
          "glyph": "\u2662",
          "href": "/governance"
        }
      ],
      "attention_count": 2,
      "attention_message": "5 items look likely to spill \u2014 review scope before close."
    },
    "CONNEXUS:34": {
      "score": 94,
      "band": "Strong",
      "caption": "Sprint 34 closed near plan",
      "completion": 100,
      "done": 75,
      "total": 75,
      "blocked": 0,
      "spillover": 0,
      "ai": 5,
      "comp": 2,
      "bugs": 224,
      "takeaways": [
        {
          "id": "blocked",
          "title": "0 items blocked",
          "subtitle": "From flagged impediments and blockers",
          "href": "/delivery-analysis?riskFocus=blockers",
          "tone": "success",
          "glyph": "\u2197"
        },
        {
          "id": "at-risk",
          "title": "0 items at risk",
          "subtitle": "Carried past Sprint 34",
          "href": "/delivery-analysis?riskFocus=schedule#schedule-risk",
          "tone": "success",
          "glyph": "\u25f7"
        },
        {
          "id": "ai",
          "title": "AI code risk at 5%",
          "subtitle": "No high-risk areas",
          "href": "/code-analysis",
          "tone": "success",
          "glyph": "</>"
        },
        {
          "id": "compliance",
          "title": "2 compliance findings",
          "subtitle": "Mock \u2014 not in Jira export",
          "href": "/governance",
          "tone": "success",
          "glyph": "\u2662"
        }
      ],
      "pillars": [
        {
          "id": "delivery",
          "name": "Delivery",
          "score": 100,
          "delta": 0,
          "footnote": "75 / 75 completed",
          "progress": 100,
          "tone": "steady",
          "glyph": "\u2691",
          "href": "/delivery-analysis"
        },
        {
          "id": "code",
          "name": "Code",
          "score": 85,
          "delta": 0,
          "footnote": "0 blocked issues",
          "progress": 85,
          "tone": "steady",
          "glyph": "</>",
          "href": "/code-analysis"
        },
        {
          "id": "qa",
          "name": "QA",
          "score": 25,
          "delta": 0,
          "footnote": "224 open bugs",
          "progress": 25,
          "tone": "danger",
          "glyph": "\u2697",
          "href": "/qa"
        },
        {
          "id": "compliance",
          "name": "Compliance",
          "score": 81,
          "delta": 0,
          "footnote": "2 open findings",
          "progress": 81,
          "tone": "steady",
          "glyph": "\u2662",
          "href": "/governance"
        }
      ],
      "attention_count": 0,
      "attention_message": "Sprint 34 delivery signals look manageable \u2014 keep owners current."
    }
  },
  "scheduleRiskBySprint": {
    "37": {
      "definition": "Open sprint work that is Highest/High priority or still To Do \u2014 likely to miss the sprint end.",
      "total": 0,
      "byTeam": [],
      "items": []
    },
    "36": {
      "definition": "Open work that remained unfinished when Sprint 36 closed.",
      "total": 0,
      "byTeam": [],
      "items": []
    },
    "35": {
      "definition": "Open work that remained unfinished when Sprint 35 closed.",
      "total": 5,
      "byTeam": [
        {
          "key": "CONNEXUS",
          "name": "Connexus",
          "count": 5
        }
      ],
      "items": [
        {
          "key": "CX-2730",
          "summary": "Date Filter Shows Feb 4 Records When Filtering for Feb 3",
          "teamKey": "CONNEXUS",
          "teamName": "Connexus",
          "priority": "Medium",
          "status": "To Do",
          "reason": "carryover"
        },
        {
          "key": "CX-3272",
          "summary": "SOW list fails to load when selecting 121+ properties during RFP creation",
          "teamKey": "CONNEXUS",
          "teamName": "Connexus",
          "priority": "Medium",
          "status": "To Do",
          "reason": "carryover"
        },
        {
          "key": "CX-3668",
          "summary": "Sentry session replay configuration for error session and frontend integration for production",
          "teamKey": "CONNEXUS",
          "teamName": "Connexus",
          "priority": "Medium",
          "status": "To Do",
          "reason": "carryover"
        },
        {
          "key": "CX-3601",
          "summary": "[Compliances demo review ] issues marked not to do",
          "teamKey": "CONNEXUS",
          "teamName": "Connexus",
          "priority": "Medium",
          "status": "Onhold",
          "reason": "carryover"
        },
        {
          "key": "CX-3650",
          "summary": "Existing vendor status cannot be changed to Exempt when the vendor status is Email Sent or Email Opened.",
          "teamKey": "CONNEXUS",
          "teamName": "Connexus",
          "priority": "Medium",
          "status": "Reopened",
          "reason": "carryover"
        }
      ]
    },
    "34": {
      "definition": "Open work that remained unfinished when Sprint 34 closed.",
      "total": 0,
      "byTeam": [],
      "items": []
    }
  },
  "scheduleRiskByTeamSprint": {
    "CONNEXUS:37": {
      "definition": "Open sprint work that is Highest/High priority or still To Do \u2014 likely to miss the sprint end.",
      "total": 0,
      "byTeam": [],
      "items": []
    },
    "CONNEXUS:36": {
      "definition": "Open work that remained unfinished when Sprint 36 closed.",
      "total": 0,
      "byTeam": [],
      "items": []
    },
    "CONNEXUS:35": {
      "definition": "Open work that remained unfinished when Sprint 35 closed.",
      "total": 5,
      "byTeam": [
        {
          "key": "CONNEXUS",
          "name": "Connexus",
          "count": 5
        }
      ],
      "items": [
        {
          "key": "CX-2730",
          "summary": "Date Filter Shows Feb 4 Records When Filtering for Feb 3",
          "teamKey": "CONNEXUS",
          "teamName": "Connexus",
          "priority": "Medium",
          "status": "To Do",
          "reason": "carryover"
        },
        {
          "key": "CX-3272",
          "summary": "SOW list fails to load when selecting 121+ properties during RFP creation",
          "teamKey": "CONNEXUS",
          "teamName": "Connexus",
          "priority": "Medium",
          "status": "To Do",
          "reason": "carryover"
        },
        {
          "key": "CX-3668",
          "summary": "Sentry session replay configuration for error session and frontend integration for production",
          "teamKey": "CONNEXUS",
          "teamName": "Connexus",
          "priority": "Medium",
          "status": "To Do",
          "reason": "carryover"
        },
        {
          "key": "CX-3601",
          "summary": "[Compliances demo review ] issues marked not to do",
          "teamKey": "CONNEXUS",
          "teamName": "Connexus",
          "priority": "Medium",
          "status": "Onhold",
          "reason": "carryover"
        },
        {
          "key": "CX-3650",
          "summary": "Existing vendor status cannot be changed to Exempt when the vendor status is Email Sent or Email Opened.",
          "teamKey": "CONNEXUS",
          "teamName": "Connexus",
          "priority": "Medium",
          "status": "Reopened",
          "reason": "carryover"
        }
      ]
    },
    "CONNEXUS:34": {
      "definition": "Open work that remained unfinished when Sprint 34 closed.",
      "total": 0,
      "byTeam": [],
      "items": []
    }
  },
  "jiraSiteUrl": "https://neoito-team-connexus.atlassian.net",
  "deliveryBySprint": {
    "37": {
      "overdue": 0,
      "resolvedLast7d": 23,
      "statusBreakdown": {
        "todo": 0,
        "inProgress": 39,
        "done": 79
      },
      "openIssues": 39,
      "missingDueDateInProgress": 39,
      "staleOpen": 12,
      "missingEstimates": 35,
      "unassigned": 0,
      "versions": [
        {
          "id": "sprint-34",
          "name": "Sprint 34",
          "released": true,
          "releaseDate": null,
          "overdue": false,
          "openIssuesInVersion": 0
        }
      ]
    },
    "36": {
      "overdue": 0,
      "resolvedLast7d": 0,
      "statusBreakdown": {
        "todo": 0,
        "inProgress": 0,
        "done": 11
      },
      "openIssues": 0,
      "missingDueDateInProgress": 0,
      "staleOpen": 0,
      "missingEstimates": 0,
      "unassigned": 0,
      "versions": []
    },
    "35": {
      "overdue": 0,
      "resolvedLast7d": 0,
      "statusBreakdown": {
        "todo": 3,
        "inProgress": 2,
        "done": 47
      },
      "openIssues": 5,
      "missingDueDateInProgress": 2,
      "staleOpen": 5,
      "missingEstimates": 5,
      "unassigned": 1,
      "versions": []
    },
    "34": {
      "overdue": 0,
      "resolvedLast7d": 0,
      "statusBreakdown": {
        "todo": 0,
        "inProgress": 0,
        "done": 75
      },
      "openIssues": 0,
      "missingDueDateInProgress": 0,
      "staleOpen": 0,
      "missingEstimates": 0,
      "unassigned": 0,
      "versions": [
        {
          "id": "sprint-34",
          "name": "Sprint 34",
          "released": true,
          "releaseDate": null,
          "overdue": false,
          "openIssuesInVersion": 0
        }
      ]
    }
  },
  "deliveryByTeamSprint": {
    "CONNEXUS:37": {
      "overdue": 0,
      "resolvedLast7d": 23,
      "statusBreakdown": {
        "todo": 0,
        "inProgress": 39,
        "done": 79
      },
      "openIssues": 39,
      "missingDueDateInProgress": 39,
      "staleOpen": 12,
      "missingEstimates": 35,
      "unassigned": 0,
      "versions": [
        {
          "id": "sprint-34",
          "name": "Sprint 34",
          "released": true,
          "releaseDate": null,
          "overdue": false,
          "openIssuesInVersion": 0
        }
      ]
    },
    "CONNEXUS:36": {
      "overdue": 0,
      "resolvedLast7d": 0,
      "statusBreakdown": {
        "todo": 0,
        "inProgress": 0,
        "done": 11
      },
      "openIssues": 0,
      "missingDueDateInProgress": 0,
      "staleOpen": 0,
      "missingEstimates": 0,
      "unassigned": 0,
      "versions": []
    },
    "CONNEXUS:35": {
      "overdue": 0,
      "resolvedLast7d": 0,
      "statusBreakdown": {
        "todo": 3,
        "inProgress": 2,
        "done": 47
      },
      "openIssues": 5,
      "missingDueDateInProgress": 2,
      "staleOpen": 5,
      "missingEstimates": 5,
      "unassigned": 1,
      "versions": []
    },
    "CONNEXUS:34": {
      "overdue": 0,
      "resolvedLast7d": 0,
      "statusBreakdown": {
        "todo": 0,
        "inProgress": 0,
        "done": 75
      },
      "openIssues": 0,
      "missingDueDateInProgress": 0,
      "staleOpen": 0,
      "missingEstimates": 0,
      "unassigned": 0,
      "versions": [
        {
          "id": "sprint-34",
          "name": "Sprint 34",
          "released": true,
          "releaseDate": null,
          "overdue": false,
          "openIssuesInVersion": 0
        }
      ]
    }
  },
  "notes": {
    "jiraSource": "fixtures/jira/cnxs.csv",
    "scope": "Latest sprint; Story/Bug/Feature/Epic only (Sub-tasks/Tasks excluded); single Connexus team",
    "mockKept": [
      "aiRisk",
      "compliance",
      "commits",
      "prs",
      "deployments",
      "leadership"
    ],
    "derived": [
      "completion",
      "blocked",
      "spillover",
      "scheduleRiskEvidence",
      "burndown",
      "jiraHeatmap",
      "trend",
      "qaOpenBugs",
      "confidenceScore",
      "deliveryVersions",
      "deliveryHygiene",
      "overdue"
    ]
  }
} as const;

export type ConnexusOverviewDerived = typeof CONNEXUS_OVERVIEW_DERIVED;
