/**
 * Overview mock derived from TPT Jira export (`/Users/musthafa/Downloads/tbt.csv`).
 * Regenerated by `scripts/generate-tpt-overview-mock.py`.
 *
 * Jira-backed: teams/sprints, completion, blocked, spillover, burndown,
 * delivery-trend proxy, Jira heatmap row, open bugs, confidence score.
 * Still mocked: AI code risk, compliance, commits/PRs/deployments rows,
 * leadership approvals.
 */
export const TPT_OVERVIEW_DERIVED = {
  "lastSyncAt": "2026-09-08T10:49:00.000Z",
  "orgName": "TPT Platform",
  "projectKey": "TP",
  "defaultSprintId": "27",
  "teams": [
    {
      "key": "AVENGERS",
      "name": "Agile Avengers"
    },
    {
      "key": "APEX",
      "name": "Apex Team"
    },
    {
      "key": "DARK",
      "name": "Dark Side Team"
    },
    {
      "key": "MOBILE",
      "name": "Mobile"
    }
  ],
  "sprints": [
    {
      "id": "27",
      "name": "Sprint 27",
      "startLabel": "Aug 31",
      "endLabel": "Sep 10",
      "rangeLabel": "31 Aug 10:27 AM \u2013 10 Sep 11:00 PM, 2026",
      "start": "2026-08-31T10:27:00.000Z",
      "end": "2026-09-10T23:00:00.000Z"
    },
    {
      "id": "26",
      "name": "Sprint 26",
      "startLabel": "Aug 17",
      "endLabel": "Aug 28",
      "rangeLabel": "17 Aug 10:24 AM \u2013 28 Aug 6:39 PM, 2026",
      "start": "2026-08-17T10:24:00.000Z",
      "end": "2026-08-28T18:39:00.000Z"
    },
    {
      "id": "25",
      "name": "Sprint 25",
      "startLabel": "Aug 3",
      "endLabel": "Aug 15",
      "rangeLabel": "3 Aug 8:07 AM \u2013 15 Aug 8:47 AM, 2026",
      "start": "2026-08-03T08:07:00.000Z",
      "end": "2026-08-15T08:47:00.000Z"
    },
    {
      "id": "24",
      "name": "Sprint 24",
      "startLabel": "Jul 20",
      "endLabel": "Aug 1",
      "rangeLabel": "20 Jul 9:17 AM \u2013 1 Aug 10:30 AM, 2026",
      "start": "2026-07-20T09:17:00.000Z",
      "end": "2026-08-01T10:30:00.000Z"
    }
  ],
  "base": {
    "score": 15,
    "band": "At risk",
    "caption": "Sprint 27 is at risk of delay",
    "completion": 30,
    "done": 74,
    "total": 244,
    "blocked": 16,
    "spillover": 52,
    "ai": 6,
    "comp": 4,
    "bugs": 113,
    "takeaways": [
      {
        "id": "blocked",
        "title": "16 items blocked",
        "subtitle": "+15 from last sprint",
        "href": "/delivery-analysis?riskFocus=blockers",
        "tone": "danger",
        "glyph": "\u2197",
        "needsAction": true
      },
      {
        "id": "at-risk",
        "title": "52 items at risk",
        "subtitle": "Likely to spill over",
        "href": "/delivery-analysis?riskFocus=schedule",
        "tone": "warning",
        "glyph": "\u25f7",
        "needsAction": true
      },
      {
        "id": "ai",
        "title": "AI code risk at 6%",
        "subtitle": "No high-risk areas",
        "href": "/code-analysis",
        "tone": "success",
        "glyph": "</>"
      },
      {
        "id": "compliance",
        "title": "4 compliance findings",
        "subtitle": "Mock \u2014 not in Jira export",
        "href": "/governance",
        "tone": "warning",
        "glyph": "\u2662",
        "needsAction": true
      }
    ],
    "pillars": [
      {
        "id": "delivery",
        "name": "Delivery",
        "score": 30,
        "delta": -59,
        "footnote": "74 / 244 completed",
        "progress": 30,
        "tone": "danger",
        "glyph": "\u2691",
        "href": "/delivery-analysis"
      },
      {
        "id": "code",
        "name": "Code",
        "score": 45,
        "delta": -37,
        "footnote": "16 blocked issues",
        "progress": 45,
        "tone": "danger",
        "glyph": "</>",
        "href": "/code-analysis"
      },
      {
        "id": "qa",
        "name": "QA",
        "score": 47,
        "delta": 0,
        "footnote": "113 open bugs",
        "progress": 47,
        "tone": "danger",
        "glyph": "\u2697",
        "href": "/qa"
      },
      {
        "id": "compliance",
        "name": "Compliance",
        "score": 67,
        "delta": 0,
        "footnote": "4 open findings",
        "progress": 67,
        "tone": "steady",
        "glyph": "\u2662",
        "href": "/governance"
      }
    ],
    "attention_count": 2,
    "attention_message": "16 blocked issues are in the evidence set \u2014 ask engineering for an owner and ETA.",
    "charts": {
      "deliveryTrend": {
        "rangeLabel": "Last 6 weeks",
        "target": 75,
        "points": [
          {
            "label": "Jul 28",
            "value": 73
          },
          {
            "label": "Aug 2",
            "value": 57
          },
          {
            "label": "Aug 6",
            "value": 58
          },
          {
            "label": "Aug 11",
            "value": 51
          },
          {
            "label": "Aug 16",
            "value": 47
          },
          {
            "label": "Aug 20",
            "value": 62
          },
          {
            "label": "Aug 25",
            "value": 56
          },
          {
            "label": "Aug 30",
            "value": 56
          },
          {
            "label": "Sep 3",
            "value": 63
          },
          {
            "label": "Sep 8",
            "value": 40
          }
        ]
      },
      "burndown": {
        "completed": 74,
        "total": 244,
        "ideal": [
          {
            "label": "Aug 26",
            "value": 244
          },
          {
            "label": "Aug 28",
            "value": 209
          },
          {
            "label": "Aug 30",
            "value": 174
          },
          {
            "label": "Sep 1",
            "value": 139
          },
          {
            "label": "Sep 2",
            "value": 105
          },
          {
            "label": "Sep 4",
            "value": 70
          },
          {
            "label": "Sep 6",
            "value": 35
          },
          {
            "label": "Sep 8",
            "value": 0
          }
        ],
        "actual": [
          {
            "label": "Aug 26",
            "value": 243
          },
          {
            "label": "Aug 28",
            "value": 242
          },
          {
            "label": "Aug 30",
            "value": 242
          },
          {
            "label": "Sep 1",
            "value": 205
          },
          {
            "label": "Sep 2",
            "value": 196
          },
          {
            "label": "Sep 4",
            "value": 177
          },
          {
            "label": "Sep 6",
            "value": 177
          },
          {
            "label": "Sep 8",
            "value": 170
          }
        ]
      },
      "heatmap": {
        "rangeLabel": "Last 2 weeks",
        "dayLabels": [
          "Aug 26",
          "Aug 27",
          "Aug 28",
          "Aug 29",
          "Aug 30",
          "Aug 31",
          "Sep 1",
          "Sep 2",
          "Sep 3",
          "Sep 4",
          "Sep 5",
          "Sep 6",
          "Sep 7",
          "Sep 8"
        ],
        "rows": [
          {
            "label": "Commits",
            "cells": [
              4,
              4,
              4,
              0,
              1,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4
            ]
          },
          {
            "label": "PRs",
            "cells": [
              4,
              4,
              4,
              0,
              2,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4
            ]
          },
          {
            "label": "Jira updates",
            "cells": [
              1,
              2,
              2,
              0,
              1,
              2,
              3,
              1,
              1,
              2,
              1,
              1,
              4,
              1
            ]
          },
          {
            "label": "Deployments",
            "cells": [
              3,
              0,
              0,
              1,
              0,
              0,
              3,
              0,
              0,
              3,
              0,
              0,
              3,
              0
            ]
          }
        ]
      }
    }
  },
  "byTeam": {
    "AVENGERS": {
      "score": 14,
      "band": "At risk",
      "caption": "Agile Avengers is at high risk of delay in Sprint 27",
      "completion": 29,
      "done": 35,
      "total": 119,
      "blocked": 14,
      "spillover": 28,
      "ai": 8,
      "comp": 2,
      "bugs": 73,
      "takeaways": [
        {
          "id": "blocked",
          "title": "14 items blocked",
          "subtitle": "+14 from last sprint",
          "href": "/delivery-analysis?riskFocus=blockers",
          "tone": "danger",
          "glyph": "\u2197",
          "needsAction": true
        },
        {
          "id": "at-risk",
          "title": "28 items at risk",
          "subtitle": "Likely to spill over",
          "href": "/delivery-analysis?riskFocus=schedule",
          "tone": "warning",
          "glyph": "\u25f7",
          "needsAction": true
        },
        {
          "id": "ai",
          "title": "AI code risk at 8%",
          "subtitle": "Watch hotspots",
          "href": "/code-analysis",
          "tone": "success",
          "glyph": "</>"
        },
        {
          "id": "compliance",
          "title": "2 compliance findings",
          "subtitle": "Mock \u2014 not in Jira export",
          "href": "/governance",
          "tone": "success",
          "glyph": "\u2662"
        }
      ],
      "pillars": [
        {
          "id": "delivery",
          "name": "Delivery",
          "score": 29,
          "delta": -71,
          "footnote": "35 / 119 completed",
          "progress": 29,
          "tone": "danger",
          "glyph": "\u2691",
          "href": "/delivery-analysis"
        },
        {
          "id": "code",
          "name": "Code",
          "score": 50,
          "delta": -35,
          "footnote": "14 blocked issues",
          "progress": 50,
          "tone": "warning",
          "glyph": "</>",
          "href": "/code-analysis"
        },
        {
          "id": "qa",
          "name": "QA",
          "score": 72,
          "delta": 0,
          "footnote": "73 open bugs",
          "progress": 72,
          "tone": "steady",
          "glyph": "\u2697",
          "href": "/qa"
        },
        {
          "id": "compliance",
          "name": "Compliance",
          "score": 81,
          "delta": 0,
          "footnote": "2 open findings",
          "progress": 81,
          "tone": "steady",
          "glyph": "\u2662",
          "href": "/governance"
        }
      ],
      "attention_count": 2,
      "attention_message": "14 blocked issues are in the evidence set \u2014 ask engineering for an owner and ETA."
    },
    "APEX": {
      "score": 50,
      "band": "Caution",
      "caption": "Sprint 27 is at risk of delay",
      "completion": 52,
      "done": 30,
      "total": 58,
      "blocked": 1,
      "spillover": 10,
      "ai": 5,
      "comp": 1,
      "bugs": 11,
      "takeaways": [
        {
          "id": "blocked",
          "title": "1 item blocked",
          "subtitle": "+1 from last sprint",
          "href": "/delivery-analysis?riskFocus=blockers",
          "tone": "success",
          "glyph": "\u2197"
        },
        {
          "id": "at-risk",
          "title": "10 items at risk",
          "subtitle": "Likely to spill over",
          "href": "/delivery-analysis?riskFocus=schedule",
          "tone": "warning",
          "glyph": "\u25f7",
          "needsAction": true
        },
        {
          "id": "ai",
          "title": "AI code risk at 5%",
          "subtitle": "No high-risk areas",
          "href": "/code-analysis",
          "tone": "success",
          "glyph": "</>"
        },
        {
          "id": "compliance",
          "title": "1 compliance finding",
          "subtitle": "Mock \u2014 not in Jira export",
          "href": "/governance",
          "tone": "success",
          "glyph": "\u2662"
        }
      ],
      "pillars": [
        {
          "id": "delivery",
          "name": "Delivery",
          "score": 52,
          "delta": -48,
          "footnote": "30 / 58 completed",
          "progress": 52,
          "tone": "warning",
          "glyph": "\u2691",
          "href": "/delivery-analysis"
        },
        {
          "id": "code",
          "name": "Code",
          "score": 82,
          "delta": -3,
          "footnote": "1 blocked issue",
          "progress": 82,
          "tone": "steady",
          "glyph": "</>",
          "href": "/code-analysis"
        },
        {
          "id": "qa",
          "name": "QA",
          "score": 87,
          "delta": 0,
          "footnote": "11 open bugs",
          "progress": 87,
          "tone": "steady",
          "glyph": "\u2697",
          "href": "/qa"
        },
        {
          "id": "compliance",
          "name": "Compliance",
          "score": 88,
          "delta": 0,
          "footnote": "1 open finding",
          "progress": 88,
          "tone": "steady",
          "glyph": "\u2662",
          "href": "/governance"
        }
      ],
      "attention_count": 2,
      "attention_message": "10 items look likely to spill \u2014 review scope before close."
    },
    "DARK": {
      "score": 14,
      "band": "At risk",
      "caption": "Dark Side Team is at high risk of delay in Sprint 27",
      "completion": 17,
      "done": 6,
      "total": 35,
      "blocked": 1,
      "spillover": 10,
      "ai": 4,
      "comp": 1,
      "bugs": 19,
      "takeaways": [
        {
          "id": "blocked",
          "title": "1 item blocked",
          "subtitle": "+1 from last sprint",
          "href": "/delivery-analysis?riskFocus=blockers",
          "tone": "success",
          "glyph": "\u2197"
        },
        {
          "id": "at-risk",
          "title": "10 items at risk",
          "subtitle": "Likely to spill over",
          "href": "/delivery-analysis?riskFocus=schedule",
          "tone": "warning",
          "glyph": "\u25f7",
          "needsAction": true
        },
        {
          "id": "ai",
          "title": "AI code risk at 4%",
          "subtitle": "No high-risk areas",
          "href": "/code-analysis",
          "tone": "success",
          "glyph": "</>"
        },
        {
          "id": "compliance",
          "title": "1 compliance finding",
          "subtitle": "Mock \u2014 not in Jira export",
          "href": "/governance",
          "tone": "success",
          "glyph": "\u2662"
        }
      ],
      "pillars": [
        {
          "id": "delivery",
          "name": "Delivery",
          "score": 17,
          "delta": -72,
          "footnote": "6 / 35 completed",
          "progress": 17,
          "tone": "danger",
          "glyph": "\u2691",
          "href": "/delivery-analysis"
        },
        {
          "id": "code",
          "name": "Code",
          "score": 82,
          "delta": -3,
          "footnote": "1 blocked issue",
          "progress": 82,
          "tone": "steady",
          "glyph": "</>",
          "href": "/code-analysis"
        },
        {
          "id": "qa",
          "name": "QA",
          "score": 85,
          "delta": 0,
          "footnote": "19 open bugs",
          "progress": 85,
          "tone": "steady",
          "glyph": "\u2697",
          "href": "/qa"
        },
        {
          "id": "compliance",
          "name": "Compliance",
          "score": 88,
          "delta": 0,
          "footnote": "1 open finding",
          "progress": 88,
          "tone": "steady",
          "glyph": "\u2662",
          "href": "/governance"
        }
      ],
      "attention_count": 2,
      "attention_message": "10 items look likely to spill \u2014 review scope before close."
    },
    "MOBILE": {
      "score": 17,
      "band": "At risk",
      "caption": "Mobile is at high risk of delay in Sprint 27",
      "completion": 18,
      "done": 3,
      "total": 17,
      "blocked": 0,
      "spillover": 3,
      "ai": 4,
      "comp": 1,
      "bugs": 6,
      "takeaways": [
        {
          "id": "blocked",
          "title": "0 items blocked",
          "subtitle": "Down from last sprint",
          "href": "/delivery-analysis?riskFocus=blockers",
          "tone": "success",
          "glyph": "\u2197"
        },
        {
          "id": "at-risk",
          "title": "3 items at risk",
          "subtitle": "Likely to spill over",
          "href": "/delivery-analysis?riskFocus=schedule",
          "tone": "info",
          "glyph": "\u25f7"
        },
        {
          "id": "ai",
          "title": "AI code risk at 4%",
          "subtitle": "No high-risk areas",
          "href": "/code-analysis",
          "tone": "success",
          "glyph": "</>"
        },
        {
          "id": "compliance",
          "title": "1 compliance finding",
          "subtitle": "Mock \u2014 not in Jira export",
          "href": "/governance",
          "tone": "success",
          "glyph": "\u2662"
        }
      ],
      "pillars": [
        {
          "id": "delivery",
          "name": "Delivery",
          "score": 18,
          "delta": 11,
          "footnote": "3 / 17 completed",
          "progress": 18,
          "tone": "danger",
          "glyph": "\u2691",
          "href": "/delivery-analysis"
        },
        {
          "id": "code",
          "name": "Code",
          "score": 85,
          "delta": 3,
          "footnote": "0 blocked issues",
          "progress": 85,
          "tone": "steady",
          "glyph": "</>",
          "href": "/code-analysis"
        },
        {
          "id": "qa",
          "name": "QA",
          "score": 88,
          "delta": 0,
          "footnote": "6 open bugs",
          "progress": 88,
          "tone": "steady",
          "glyph": "\u2697",
          "href": "/qa"
        },
        {
          "id": "compliance",
          "name": "Compliance",
          "score": 88,
          "delta": 0,
          "footnote": "1 open finding",
          "progress": 88,
          "tone": "steady",
          "glyph": "\u2662",
          "href": "/governance"
        }
      ],
      "attention_count": 1,
      "attention_message": "Sprint 27 delivery signals look manageable \u2014 keep owners current."
    }
  },
  "bySprint": {
    "24": {
      "kpis": {
        "score": 91,
        "band": "Strong",
        "caption": "Sprint 24 closed near plan",
        "completion": 96,
        "done": 139,
        "total": 145,
        "blocked": 0,
        "spillover": 6,
        "ai": 6,
        "comp": 4,
        "bugs": 113,
        "takeaways": [
          {
            "id": "blocked",
            "title": "0 items blocked",
            "subtitle": "From flagged impediments and blockers",
            "href": "/delivery-analysis?riskFocus=blockers",
            "tone": "success",
            "glyph": "\u2197"
          },
          {
            "id": "at-risk",
            "title": "6 items at risk",
            "subtitle": "Carried past Sprint 24",
            "href": "/delivery-analysis?riskFocus=schedule",
            "tone": "warning",
            "glyph": "\u25f7",
            "needsAction": true
          },
          {
            "id": "ai",
            "title": "AI code risk at 6%",
            "subtitle": "No high-risk areas",
            "href": "/code-analysis",
            "tone": "success",
            "glyph": "</>"
          },
          {
            "id": "compliance",
            "title": "4 compliance findings",
            "subtitle": "Mock \u2014 not in Jira export",
            "href": "/governance",
            "tone": "warning",
            "glyph": "\u2662",
            "needsAction": true
          }
        ],
        "pillars": [
          {
            "id": "delivery",
            "name": "Delivery",
            "score": 96,
            "delta": 0,
            "footnote": "139 / 145 completed",
            "progress": 96,
            "tone": "steady",
            "glyph": "\u2691",
            "href": "/delivery-analysis"
          },
          {
            "id": "code",
            "name": "Code",
            "score": 85,
            "delta": 0,
            "footnote": "0 blocked issues",
            "progress": 85,
            "tone": "steady",
            "glyph": "</>",
            "href": "/code-analysis"
          },
          {
            "id": "qa",
            "name": "QA",
            "score": 47,
            "delta": 0,
            "footnote": "113 open bugs",
            "progress": 47,
            "tone": "danger",
            "glyph": "\u2697",
            "href": "/qa"
          },
          {
            "id": "compliance",
            "name": "Compliance",
            "score": 67,
            "delta": 0,
            "footnote": "4 open findings",
            "progress": 67,
            "tone": "steady",
            "glyph": "\u2662",
            "href": "/governance"
          }
        ],
        "attention_count": 2,
        "attention_message": "6 items look likely to spill \u2014 review scope before close."
      },
      "charts": {
        "deliveryTrend": {
          "rangeLabel": "Last 6 weeks",
          "target": 75,
          "points": [
            {
              "label": "Jun 16",
              "value": 50
            },
            {
              "label": "Jun 21",
              "value": 60
            },
            {
              "label": "Jun 25",
              "value": 65
            },
            {
              "label": "Jun 30",
              "value": 46
            },
            {
              "label": "Jul 5",
              "value": 65
            },
            {
              "label": "Jul 9",
              "value": 60
            },
            {
              "label": "Jul 14",
              "value": 51
            },
            {
              "label": "Jul 19",
              "value": 63
            },
            {
              "label": "Jul 23",
              "value": 58
            },
            {
              "label": "Jul 28",
              "value": 83
            }
          ]
        },
        "burndown": {
          "completed": 139,
          "total": 145,
          "ideal": [
            {
              "label": "Jul 15",
              "value": 145
            },
            {
              "label": "Jul 17",
              "value": 124
            },
            {
              "label": "Jul 19",
              "value": 104
            },
            {
              "label": "Jul 21",
              "value": 83
            },
            {
              "label": "Jul 22",
              "value": 62
            },
            {
              "label": "Jul 24",
              "value": 41
            },
            {
              "label": "Jul 26",
              "value": 21
            },
            {
              "label": "Jul 28",
              "value": 0
            }
          ],
          "actual": [
            {
              "label": "Jul 15",
              "value": 145
            },
            {
              "label": "Jul 17",
              "value": 145
            },
            {
              "label": "Jul 19",
              "value": 145
            },
            {
              "label": "Jul 21",
              "value": 128
            },
            {
              "label": "Jul 22",
              "value": 117
            },
            {
              "label": "Jul 24",
              "value": 87
            },
            {
              "label": "Jul 26",
              "value": 87
            },
            {
              "label": "Jul 28",
              "value": 75
            }
          ]
        },
        "heatmap": {
          "rangeLabel": "Last 2 weeks",
          "dayLabels": [
            "Jul 15",
            "Jul 16",
            "Jul 17",
            "Jul 18",
            "Jul 19",
            "Jul 20",
            "Jul 21",
            "Jul 22",
            "Jul 23",
            "Jul 24",
            "Jul 25",
            "Jul 26",
            "Jul 27",
            "Jul 28"
          ],
          "rows": [
            {
              "label": "Commits",
              "cells": [
                4,
                4,
                4,
                4,
                1,
                4,
                4,
                4,
                4,
                4,
                0,
                0,
                4,
                4
              ]
            },
            {
              "label": "PRs",
              "cells": [
                4,
                4,
                4,
                4,
                2,
                4,
                4,
                4,
                4,
                4,
                1,
                0,
                4,
                4
              ]
            },
            {
              "label": "Jira updates",
              "cells": [
                2,
                1,
                4,
                1,
                1,
                2,
                2,
                2,
                3,
                2,
                0,
                0,
                1,
                2
              ]
            },
            {
              "label": "Deployments",
              "cells": [
                3,
                0,
                0,
                3,
                0,
                0,
                3,
                0,
                0,
                3,
                0,
                0,
                2,
                0
              ]
            }
          ]
        }
      }
    },
    "25": {
      "kpis": {
        "score": 69,
        "band": "Steady",
        "caption": "Sprint 25 closed with carry-over",
        "completion": 79,
        "done": 96,
        "total": 122,
        "blocked": 4,
        "spillover": 26,
        "ai": 6,
        "comp": 4,
        "bugs": 113,
        "takeaways": [
          {
            "id": "blocked",
            "title": "4 items blocked",
            "subtitle": "+4 from last sprint",
            "href": "/delivery-analysis?riskFocus=blockers",
            "tone": "warning",
            "glyph": "\u2197",
            "needsAction": true
          },
          {
            "id": "at-risk",
            "title": "26 items at risk",
            "subtitle": "Carried past Sprint 25",
            "href": "/delivery-analysis?riskFocus=schedule",
            "tone": "warning",
            "glyph": "\u25f7",
            "needsAction": true
          },
          {
            "id": "ai",
            "title": "AI code risk at 6%",
            "subtitle": "No high-risk areas",
            "href": "/code-analysis",
            "tone": "success",
            "glyph": "</>"
          },
          {
            "id": "compliance",
            "title": "4 compliance findings",
            "subtitle": "Mock \u2014 not in Jira export",
            "href": "/governance",
            "tone": "warning",
            "glyph": "\u2662",
            "needsAction": true
          }
        ],
        "pillars": [
          {
            "id": "delivery",
            "name": "Delivery",
            "score": 79,
            "delta": -17,
            "footnote": "96 / 122 completed",
            "progress": 79,
            "tone": "steady",
            "glyph": "\u2691",
            "href": "/delivery-analysis"
          },
          {
            "id": "code",
            "name": "Code",
            "score": 75,
            "delta": -10,
            "footnote": "4 blocked issues",
            "progress": 75,
            "tone": "steady",
            "glyph": "</>",
            "href": "/code-analysis"
          },
          {
            "id": "qa",
            "name": "QA",
            "score": 47,
            "delta": 0,
            "footnote": "113 open bugs",
            "progress": 47,
            "tone": "danger",
            "glyph": "\u2697",
            "href": "/qa"
          },
          {
            "id": "compliance",
            "name": "Compliance",
            "score": 67,
            "delta": 0,
            "footnote": "4 open findings",
            "progress": 67,
            "tone": "steady",
            "glyph": "\u2662",
            "href": "/governance"
          }
        ],
        "attention_count": 2,
        "attention_message": "4 blocked issues are in the evidence set \u2014 ask engineering for an owner and ETA."
      },
      "charts": {
        "deliveryTrend": {
          "rangeLabel": "Last 6 weeks",
          "target": 75,
          "points": [
            {
              "label": "Jun 30",
              "value": 46
            },
            {
              "label": "Jul 5",
              "value": 65
            },
            {
              "label": "Jul 9",
              "value": 60
            },
            {
              "label": "Jul 14",
              "value": 51
            },
            {
              "label": "Jul 19",
              "value": 63
            },
            {
              "label": "Jul 23",
              "value": 58
            },
            {
              "label": "Jul 28",
              "value": 73
            },
            {
              "label": "Aug 2",
              "value": 57
            },
            {
              "label": "Aug 6",
              "value": 58
            },
            {
              "label": "Aug 11",
              "value": 64
            }
          ]
        },
        "burndown": {
          "completed": 96,
          "total": 122,
          "ideal": [
            {
              "label": "Jul 29",
              "value": 122
            },
            {
              "label": "Jul 31",
              "value": 105
            },
            {
              "label": "Aug 2",
              "value": 87
            },
            {
              "label": "Aug 4",
              "value": 70
            },
            {
              "label": "Aug 5",
              "value": 52
            },
            {
              "label": "Aug 7",
              "value": 35
            },
            {
              "label": "Aug 9",
              "value": 17
            },
            {
              "label": "Aug 11",
              "value": 0
            }
          ],
          "actual": [
            {
              "label": "Jul 29",
              "value": 122
            },
            {
              "label": "Jul 31",
              "value": 122
            },
            {
              "label": "Aug 2",
              "value": 122
            },
            {
              "label": "Aug 4",
              "value": 109
            },
            {
              "label": "Aug 5",
              "value": 103
            },
            {
              "label": "Aug 7",
              "value": 82
            },
            {
              "label": "Aug 9",
              "value": 81
            },
            {
              "label": "Aug 11",
              "value": 67
            }
          ]
        },
        "heatmap": {
          "rangeLabel": "Last 2 weeks",
          "dayLabels": [
            "Jul 29",
            "Jul 30",
            "Jul 31",
            "Aug 1",
            "Aug 2",
            "Aug 3",
            "Aug 4",
            "Aug 5",
            "Aug 6",
            "Aug 7",
            "Aug 8",
            "Aug 9",
            "Aug 10",
            "Aug 11"
          ],
          "rows": [
            {
              "label": "Commits",
              "cells": [
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                3,
                3,
                4,
                4
              ]
            },
            {
              "label": "PRs",
              "cells": [
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                3,
                0,
                4,
                4
              ]
            },
            {
              "label": "Jira updates",
              "cells": [
                2,
                2,
                1,
                1,
                1,
                1,
                2,
                4,
                1,
                1,
                1,
                1,
                1,
                1
              ]
            },
            {
              "label": "Deployments",
              "cells": [
                3,
                0,
                0,
                3,
                0,
                0,
                3,
                0,
                0,
                3,
                0,
                0,
                3,
                0
              ]
            }
          ]
        }
      }
    },
    "26": {
      "kpis": {
        "score": 82,
        "band": "Strong",
        "caption": "Sprint 26 closed with carry-over",
        "completion": 89,
        "done": 123,
        "total": 138,
        "blocked": 1,
        "spillover": 15,
        "ai": 6,
        "comp": 4,
        "bugs": 113,
        "takeaways": [
          {
            "id": "blocked",
            "title": "1 item blocked",
            "subtitle": "Down from last sprint",
            "href": "/delivery-analysis?riskFocus=blockers",
            "tone": "success",
            "glyph": "\u2197"
          },
          {
            "id": "at-risk",
            "title": "15 items at risk",
            "subtitle": "Carried past Sprint 26",
            "href": "/delivery-analysis?riskFocus=schedule",
            "tone": "warning",
            "glyph": "\u25f7",
            "needsAction": true
          },
          {
            "id": "ai",
            "title": "AI code risk at 6%",
            "subtitle": "No high-risk areas",
            "href": "/code-analysis",
            "tone": "success",
            "glyph": "</>"
          },
          {
            "id": "compliance",
            "title": "4 compliance findings",
            "subtitle": "Mock \u2014 not in Jira export",
            "href": "/governance",
            "tone": "warning",
            "glyph": "\u2662",
            "needsAction": true
          }
        ],
        "pillars": [
          {
            "id": "delivery",
            "name": "Delivery",
            "score": 89,
            "delta": 10,
            "footnote": "123 / 138 completed",
            "progress": 89,
            "tone": "steady",
            "glyph": "\u2691",
            "href": "/delivery-analysis"
          },
          {
            "id": "code",
            "name": "Code",
            "score": 82,
            "delta": 7,
            "footnote": "1 blocked issue",
            "progress": 82,
            "tone": "steady",
            "glyph": "</>",
            "href": "/code-analysis"
          },
          {
            "id": "qa",
            "name": "QA",
            "score": 47,
            "delta": 0,
            "footnote": "113 open bugs",
            "progress": 47,
            "tone": "danger",
            "glyph": "\u2697",
            "href": "/qa"
          },
          {
            "id": "compliance",
            "name": "Compliance",
            "score": 67,
            "delta": 0,
            "footnote": "4 open findings",
            "progress": 67,
            "tone": "steady",
            "glyph": "\u2662",
            "href": "/governance"
          }
        ],
        "attention_count": 2,
        "attention_message": "15 items look likely to spill \u2014 review scope before close."
      },
      "charts": {
        "deliveryTrend": {
          "rangeLabel": "Last 6 weeks",
          "target": 75,
          "points": [
            {
              "label": "Jul 14",
              "value": 51
            },
            {
              "label": "Jul 19",
              "value": 63
            },
            {
              "label": "Jul 23",
              "value": 58
            },
            {
              "label": "Jul 28",
              "value": 73
            },
            {
              "label": "Aug 2",
              "value": 57
            },
            {
              "label": "Aug 6",
              "value": 58
            },
            {
              "label": "Aug 11",
              "value": 51
            },
            {
              "label": "Aug 16",
              "value": 47
            },
            {
              "label": "Aug 20",
              "value": 62
            },
            {
              "label": "Aug 25",
              "value": 71
            }
          ]
        },
        "burndown": {
          "completed": 123,
          "total": 138,
          "ideal": [
            {
              "label": "Aug 12",
              "value": 138
            },
            {
              "label": "Aug 14",
              "value": 118
            },
            {
              "label": "Aug 16",
              "value": 99
            },
            {
              "label": "Aug 18",
              "value": 79
            },
            {
              "label": "Aug 19",
              "value": 59
            },
            {
              "label": "Aug 21",
              "value": 39
            },
            {
              "label": "Aug 23",
              "value": 20
            },
            {
              "label": "Aug 25",
              "value": 0
            }
          ],
          "actual": [
            {
              "label": "Aug 12",
              "value": 138
            },
            {
              "label": "Aug 14",
              "value": 137
            },
            {
              "label": "Aug 16",
              "value": 136
            },
            {
              "label": "Aug 18",
              "value": 114
            },
            {
              "label": "Aug 19",
              "value": 93
            },
            {
              "label": "Aug 21",
              "value": 63
            },
            {
              "label": "Aug 23",
              "value": 62
            },
            {
              "label": "Aug 25",
              "value": 55
            }
          ]
        },
        "heatmap": {
          "rangeLabel": "Last 2 weeks",
          "dayLabels": [
            "Aug 12",
            "Aug 13",
            "Aug 14",
            "Aug 15",
            "Aug 16",
            "Aug 17",
            "Aug 18",
            "Aug 19",
            "Aug 20",
            "Aug 21",
            "Aug 22",
            "Aug 23",
            "Aug 24",
            "Aug 25"
          ],
          "rows": [
            {
              "label": "Commits",
              "cells": [
                4,
                4,
                4,
                3,
                1,
                4,
                4,
                4,
                4,
                4,
                1,
                4,
                4,
                4
              ]
            },
            {
              "label": "PRs",
              "cells": [
                4,
                4,
                4,
                3,
                2,
                4,
                4,
                4,
                4,
                4,
                2,
                4,
                4,
                4
              ]
            },
            {
              "label": "Jira updates",
              "cells": [
                3,
                2,
                3,
                1,
                1,
                3,
                2,
                3,
                3,
                4,
                1,
                1,
                1,
                2
              ]
            },
            {
              "label": "Deployments",
              "cells": [
                3,
                0,
                0,
                2,
                0,
                0,
                3,
                0,
                0,
                3,
                0,
                0,
                3,
                0
              ]
            }
          ]
        }
      }
    }
  },
  "byTeamSprint": {
    "AVENGERS:24": {
      "score": 97,
      "band": "Strong",
      "caption": "Sprint 24 closed near plan",
      "completion": 100,
      "done": 30,
      "total": 30,
      "blocked": 0,
      "spillover": 0,
      "ai": 8,
      "comp": 2,
      "bugs": 73,
      "takeaways": [
        {
          "id": "blocked",
          "title": "0 items blocked",
          "subtitle": "From flagged impediments and blockers",
          "href": "/delivery-analysis?riskFocus=blockers",
          "tone": "success",
          "glyph": "\u2197"
        },
        {
          "id": "at-risk",
          "title": "0 items at risk",
          "subtitle": "Carried past Sprint 24",
          "href": "/delivery-analysis?riskFocus=schedule",
          "tone": "success",
          "glyph": "\u25f7"
        },
        {
          "id": "ai",
          "title": "AI code risk at 8%",
          "subtitle": "Watch hotspots",
          "href": "/code-analysis",
          "tone": "success",
          "glyph": "</>"
        },
        {
          "id": "compliance",
          "title": "2 compliance findings",
          "subtitle": "Mock \u2014 not in Jira export",
          "href": "/governance",
          "tone": "success",
          "glyph": "\u2662"
        }
      ],
      "pillars": [
        {
          "id": "delivery",
          "name": "Delivery",
          "score": 100,
          "delta": 0,
          "footnote": "30 / 30 completed",
          "progress": 100,
          "tone": "steady",
          "glyph": "\u2691",
          "href": "/delivery-analysis"
        },
        {
          "id": "code",
          "name": "Code",
          "score": 85,
          "delta": 0,
          "footnote": "0 blocked issues",
          "progress": 85,
          "tone": "steady",
          "glyph": "</>",
          "href": "/code-analysis"
        },
        {
          "id": "qa",
          "name": "QA",
          "score": 72,
          "delta": 0,
          "footnote": "73 open bugs",
          "progress": 72,
          "tone": "steady",
          "glyph": "\u2697",
          "href": "/qa"
        },
        {
          "id": "compliance",
          "name": "Compliance",
          "score": 81,
          "delta": 0,
          "footnote": "2 open findings",
          "progress": 81,
          "tone": "steady",
          "glyph": "\u2662",
          "href": "/governance"
        }
      ],
      "attention_count": 0,
      "attention_message": "Sprint 24 delivery signals look manageable \u2014 keep owners current."
    },
    "APEX:24": {
      "score": 96,
      "band": "Strong",
      "caption": "Sprint 24 closed near plan",
      "completion": 97,
      "done": 73,
      "total": 75,
      "blocked": 0,
      "spillover": 2,
      "ai": 5,
      "comp": 1,
      "bugs": 11,
      "takeaways": [
        {
          "id": "blocked",
          "title": "0 items blocked",
          "subtitle": "From flagged impediments and blockers",
          "href": "/delivery-analysis?riskFocus=blockers",
          "tone": "success",
          "glyph": "\u2197"
        },
        {
          "id": "at-risk",
          "title": "2 items at risk",
          "subtitle": "Carried past Sprint 24",
          "href": "/delivery-analysis?riskFocus=schedule",
          "tone": "info",
          "glyph": "\u25f7"
        },
        {
          "id": "ai",
          "title": "AI code risk at 5%",
          "subtitle": "No high-risk areas",
          "href": "/code-analysis",
          "tone": "success",
          "glyph": "</>"
        },
        {
          "id": "compliance",
          "title": "1 compliance finding",
          "subtitle": "Mock \u2014 not in Jira export",
          "href": "/governance",
          "tone": "success",
          "glyph": "\u2662"
        }
      ],
      "pillars": [
        {
          "id": "delivery",
          "name": "Delivery",
          "score": 97,
          "delta": 0,
          "footnote": "73 / 75 completed",
          "progress": 97,
          "tone": "steady",
          "glyph": "\u2691",
          "href": "/delivery-analysis"
        },
        {
          "id": "code",
          "name": "Code",
          "score": 85,
          "delta": 0,
          "footnote": "0 blocked issues",
          "progress": 85,
          "tone": "steady",
          "glyph": "</>",
          "href": "/code-analysis"
        },
        {
          "id": "qa",
          "name": "QA",
          "score": 87,
          "delta": 0,
          "footnote": "11 open bugs",
          "progress": 87,
          "tone": "steady",
          "glyph": "\u2697",
          "href": "/qa"
        },
        {
          "id": "compliance",
          "name": "Compliance",
          "score": 88,
          "delta": 0,
          "footnote": "1 open finding",
          "progress": 88,
          "tone": "steady",
          "glyph": "\u2662",
          "href": "/governance"
        }
      ],
      "attention_count": 1,
      "attention_message": "Sprint 24 delivery signals look manageable \u2014 keep owners current."
    },
    "DARK:24": {
      "score": 88,
      "band": "Strong",
      "caption": "Sprint 24 closed with carry-over",
      "completion": 89,
      "done": 31,
      "total": 35,
      "blocked": 0,
      "spillover": 4,
      "ai": 4,
      "comp": 1,
      "bugs": 19,
      "takeaways": [
        {
          "id": "blocked",
          "title": "0 items blocked",
          "subtitle": "From flagged impediments and blockers",
          "href": "/delivery-analysis?riskFocus=blockers",
          "tone": "success",
          "glyph": "\u2197"
        },
        {
          "id": "at-risk",
          "title": "4 items at risk",
          "subtitle": "Carried past Sprint 24",
          "href": "/delivery-analysis?riskFocus=schedule",
          "tone": "info",
          "glyph": "\u25f7"
        },
        {
          "id": "ai",
          "title": "AI code risk at 4%",
          "subtitle": "No high-risk areas",
          "href": "/code-analysis",
          "tone": "success",
          "glyph": "</>"
        },
        {
          "id": "compliance",
          "title": "1 compliance finding",
          "subtitle": "Mock \u2014 not in Jira export",
          "href": "/governance",
          "tone": "success",
          "glyph": "\u2662"
        }
      ],
      "pillars": [
        {
          "id": "delivery",
          "name": "Delivery",
          "score": 89,
          "delta": 0,
          "footnote": "31 / 35 completed",
          "progress": 89,
          "tone": "steady",
          "glyph": "\u2691",
          "href": "/delivery-analysis"
        },
        {
          "id": "code",
          "name": "Code",
          "score": 85,
          "delta": 0,
          "footnote": "0 blocked issues",
          "progress": 85,
          "tone": "steady",
          "glyph": "</>",
          "href": "/code-analysis"
        },
        {
          "id": "qa",
          "name": "QA",
          "score": 85,
          "delta": 0,
          "footnote": "19 open bugs",
          "progress": 85,
          "tone": "steady",
          "glyph": "\u2697",
          "href": "/qa"
        },
        {
          "id": "compliance",
          "name": "Compliance",
          "score": 88,
          "delta": 0,
          "footnote": "1 open finding",
          "progress": 88,
          "tone": "steady",
          "glyph": "\u2662",
          "href": "/governance"
        }
      ],
      "attention_count": 1,
      "attention_message": "Sprint 24 delivery signals look manageable \u2014 keep owners current."
    },
    "MOBILE:24": {
      "score": 0,
      "band": "At risk",
      "caption": "Sprint 24 closed behind plan",
      "completion": 0,
      "done": 0,
      "total": 0,
      "blocked": 0,
      "spillover": 0,
      "ai": 4,
      "comp": 1,
      "bugs": 6,
      "takeaways": [
        {
          "id": "blocked",
          "title": "0 items blocked",
          "subtitle": "From flagged impediments and blockers",
          "href": "/delivery-analysis?riskFocus=blockers",
          "tone": "success",
          "glyph": "\u2197"
        },
        {
          "id": "at-risk",
          "title": "0 items at risk",
          "subtitle": "Carried past Sprint 24",
          "href": "/delivery-analysis?riskFocus=schedule",
          "tone": "success",
          "glyph": "\u25f7"
        },
        {
          "id": "ai",
          "title": "AI code risk at 4%",
          "subtitle": "No high-risk areas",
          "href": "/code-analysis",
          "tone": "success",
          "glyph": "</>"
        },
        {
          "id": "compliance",
          "title": "1 compliance finding",
          "subtitle": "Mock \u2014 not in Jira export",
          "href": "/governance",
          "tone": "success",
          "glyph": "\u2662"
        }
      ],
      "pillars": [
        {
          "id": "delivery",
          "name": "Delivery",
          "score": 0,
          "delta": 0,
          "footnote": "0 / 0 completed",
          "progress": 0,
          "tone": "danger",
          "glyph": "\u2691",
          "href": "/delivery-analysis"
        },
        {
          "id": "code",
          "name": "Code",
          "score": 85,
          "delta": 0,
          "footnote": "0 blocked issues",
          "progress": 85,
          "tone": "steady",
          "glyph": "</>",
          "href": "/code-analysis"
        },
        {
          "id": "qa",
          "name": "QA",
          "score": 88,
          "delta": 0,
          "footnote": "6 open bugs",
          "progress": 88,
          "tone": "steady",
          "glyph": "\u2697",
          "href": "/qa"
        },
        {
          "id": "compliance",
          "name": "Compliance",
          "score": 88,
          "delta": 0,
          "footnote": "1 open finding",
          "progress": 88,
          "tone": "steady",
          "glyph": "\u2662",
          "href": "/governance"
        }
      ],
      "attention_count": 0,
      "attention_message": "Sprint 24 delivery signals look manageable \u2014 keep owners current."
    },
    "AVENGERS:25": {
      "score": 89,
      "band": "Strong",
      "caption": "Sprint 25 closed near plan",
      "completion": 92,
      "done": 37,
      "total": 40,
      "blocked": 0,
      "spillover": 3,
      "ai": 8,
      "comp": 2,
      "bugs": 73,
      "takeaways": [
        {
          "id": "blocked",
          "title": "0 items blocked",
          "subtitle": "Flat vs last sprint",
          "href": "/delivery-analysis?riskFocus=blockers",
          "tone": "success",
          "glyph": "\u2197"
        },
        {
          "id": "at-risk",
          "title": "3 items at risk",
          "subtitle": "Carried past Sprint 25",
          "href": "/delivery-analysis?riskFocus=schedule",
          "tone": "info",
          "glyph": "\u25f7"
        },
        {
          "id": "ai",
          "title": "AI code risk at 8%",
          "subtitle": "Watch hotspots",
          "href": "/code-analysis",
          "tone": "success",
          "glyph": "</>"
        },
        {
          "id": "compliance",
          "title": "2 compliance findings",
          "subtitle": "Mock \u2014 not in Jira export",
          "href": "/governance",
          "tone": "success",
          "glyph": "\u2662"
        }
      ],
      "pillars": [
        {
          "id": "delivery",
          "name": "Delivery",
          "score": 92,
          "delta": -8,
          "footnote": "37 / 40 completed",
          "progress": 92,
          "tone": "steady",
          "glyph": "\u2691",
          "href": "/delivery-analysis"
        },
        {
          "id": "code",
          "name": "Code",
          "score": 85,
          "delta": 0,
          "footnote": "0 blocked issues",
          "progress": 85,
          "tone": "steady",
          "glyph": "</>",
          "href": "/code-analysis"
        },
        {
          "id": "qa",
          "name": "QA",
          "score": 72,
          "delta": 0,
          "footnote": "73 open bugs",
          "progress": 72,
          "tone": "steady",
          "glyph": "\u2697",
          "href": "/qa"
        },
        {
          "id": "compliance",
          "name": "Compliance",
          "score": 81,
          "delta": 0,
          "footnote": "2 open findings",
          "progress": 81,
          "tone": "steady",
          "glyph": "\u2662",
          "href": "/governance"
        }
      ],
      "attention_count": 1,
      "attention_message": "Sprint 25 delivery signals look manageable \u2014 keep owners current."
    },
    "APEX:25": {
      "score": 91,
      "band": "Strong",
      "caption": "Sprint 25 closed near plan",
      "completion": 92,
      "done": 24,
      "total": 26,
      "blocked": 1,
      "spillover": 2,
      "ai": 5,
      "comp": 1,
      "bugs": 11,
      "takeaways": [
        {
          "id": "blocked",
          "title": "1 item blocked",
          "subtitle": "+1 from last sprint",
          "href": "/delivery-analysis?riskFocus=blockers",
          "tone": "success",
          "glyph": "\u2197"
        },
        {
          "id": "at-risk",
          "title": "2 items at risk",
          "subtitle": "Carried past Sprint 25",
          "href": "/delivery-analysis?riskFocus=schedule",
          "tone": "info",
          "glyph": "\u25f7"
        },
        {
          "id": "ai",
          "title": "AI code risk at 5%",
          "subtitle": "No high-risk areas",
          "href": "/code-analysis",
          "tone": "success",
          "glyph": "</>"
        },
        {
          "id": "compliance",
          "title": "1 compliance finding",
          "subtitle": "Mock \u2014 not in Jira export",
          "href": "/governance",
          "tone": "success",
          "glyph": "\u2662"
        }
      ],
      "pillars": [
        {
          "id": "delivery",
          "name": "Delivery",
          "score": 92,
          "delta": -5,
          "footnote": "24 / 26 completed",
          "progress": 92,
          "tone": "steady",
          "glyph": "\u2691",
          "href": "/delivery-analysis"
        },
        {
          "id": "code",
          "name": "Code",
          "score": 82,
          "delta": -3,
          "footnote": "1 blocked issue",
          "progress": 82,
          "tone": "steady",
          "glyph": "</>",
          "href": "/code-analysis"
        },
        {
          "id": "qa",
          "name": "QA",
          "score": 87,
          "delta": 0,
          "footnote": "11 open bugs",
          "progress": 87,
          "tone": "steady",
          "glyph": "\u2697",
          "href": "/qa"
        },
        {
          "id": "compliance",
          "name": "Compliance",
          "score": 88,
          "delta": 0,
          "footnote": "1 open finding",
          "progress": 88,
          "tone": "steady",
          "glyph": "\u2662",
          "href": "/governance"
        }
      ],
      "attention_count": 1,
      "attention_message": "Sprint 25 delivery signals look manageable \u2014 keep owners current."
    },
    "DARK:25": {
      "score": 93,
      "band": "Strong",
      "caption": "Sprint 25 closed near plan",
      "completion": 94,
      "done": 31,
      "total": 33,
      "blocked": 0,
      "spillover": 2,
      "ai": 4,
      "comp": 1,
      "bugs": 19,
      "takeaways": [
        {
          "id": "blocked",
          "title": "0 items blocked",
          "subtitle": "Flat vs last sprint",
          "href": "/delivery-analysis?riskFocus=blockers",
          "tone": "success",
          "glyph": "\u2197"
        },
        {
          "id": "at-risk",
          "title": "2 items at risk",
          "subtitle": "Carried past Sprint 25",
          "href": "/delivery-analysis?riskFocus=schedule",
          "tone": "info",
          "glyph": "\u25f7"
        },
        {
          "id": "ai",
          "title": "AI code risk at 4%",
          "subtitle": "No high-risk areas",
          "href": "/code-analysis",
          "tone": "success",
          "glyph": "</>"
        },
        {
          "id": "compliance",
          "title": "1 compliance finding",
          "subtitle": "Mock \u2014 not in Jira export",
          "href": "/governance",
          "tone": "success",
          "glyph": "\u2662"
        }
      ],
      "pillars": [
        {
          "id": "delivery",
          "name": "Delivery",
          "score": 94,
          "delta": 5,
          "footnote": "31 / 33 completed",
          "progress": 94,
          "tone": "steady",
          "glyph": "\u2691",
          "href": "/delivery-analysis"
        },
        {
          "id": "code",
          "name": "Code",
          "score": 85,
          "delta": 0,
          "footnote": "0 blocked issues",
          "progress": 85,
          "tone": "steady",
          "glyph": "</>",
          "href": "/code-analysis"
        },
        {
          "id": "qa",
          "name": "QA",
          "score": 85,
          "delta": 0,
          "footnote": "19 open bugs",
          "progress": 85,
          "tone": "steady",
          "glyph": "\u2697",
          "href": "/qa"
        },
        {
          "id": "compliance",
          "name": "Compliance",
          "score": 88,
          "delta": 0,
          "footnote": "1 open finding",
          "progress": 88,
          "tone": "steady",
          "glyph": "\u2662",
          "href": "/governance"
        }
      ],
      "attention_count": 1,
      "attention_message": "Sprint 25 delivery signals look manageable \u2014 keep owners current."
    },
    "MOBILE:25": {
      "score": 13,
      "band": "At risk",
      "caption": "Sprint 25 closed behind plan",
      "completion": 17,
      "done": 4,
      "total": 23,
      "blocked": 3,
      "spillover": 19,
      "ai": 4,
      "comp": 1,
      "bugs": 6,
      "takeaways": [
        {
          "id": "blocked",
          "title": "3 items blocked",
          "subtitle": "+3 from last sprint",
          "href": "/delivery-analysis?riskFocus=blockers",
          "tone": "warning",
          "glyph": "\u2197",
          "needsAction": true
        },
        {
          "id": "at-risk",
          "title": "19 items at risk",
          "subtitle": "Carried past Sprint 25",
          "href": "/delivery-analysis?riskFocus=schedule",
          "tone": "warning",
          "glyph": "\u25f7",
          "needsAction": true
        },
        {
          "id": "ai",
          "title": "AI code risk at 4%",
          "subtitle": "No high-risk areas",
          "href": "/code-analysis",
          "tone": "success",
          "glyph": "</>"
        },
        {
          "id": "compliance",
          "title": "1 compliance finding",
          "subtitle": "Mock \u2014 not in Jira export",
          "href": "/governance",
          "tone": "success",
          "glyph": "\u2662"
        }
      ],
      "pillars": [
        {
          "id": "delivery",
          "name": "Delivery",
          "score": 17,
          "delta": 17,
          "footnote": "4 / 23 completed",
          "progress": 17,
          "tone": "danger",
          "glyph": "\u2691",
          "href": "/delivery-analysis"
        },
        {
          "id": "code",
          "name": "Code",
          "score": 78,
          "delta": -7,
          "footnote": "3 blocked issues",
          "progress": 78,
          "tone": "steady",
          "glyph": "</>",
          "href": "/code-analysis"
        },
        {
          "id": "qa",
          "name": "QA",
          "score": 88,
          "delta": 0,
          "footnote": "6 open bugs",
          "progress": 88,
          "tone": "steady",
          "glyph": "\u2697",
          "href": "/qa"
        },
        {
          "id": "compliance",
          "name": "Compliance",
          "score": 88,
          "delta": 0,
          "footnote": "1 open finding",
          "progress": 88,
          "tone": "steady",
          "glyph": "\u2662",
          "href": "/governance"
        }
      ],
      "attention_count": 2,
      "attention_message": "3 blocked issues are in the evidence set \u2014 ask engineering for an owner and ETA."
    },
    "AVENGERS:26": {
      "score": 97,
      "band": "Strong",
      "caption": "Sprint 26 closed near plan",
      "completion": 100,
      "done": 74,
      "total": 74,
      "blocked": 0,
      "spillover": 0,
      "ai": 8,
      "comp": 2,
      "bugs": 73,
      "takeaways": [
        {
          "id": "blocked",
          "title": "0 items blocked",
          "subtitle": "Flat vs last sprint",
          "href": "/delivery-analysis?riskFocus=blockers",
          "tone": "success",
          "glyph": "\u2197"
        },
        {
          "id": "at-risk",
          "title": "0 items at risk",
          "subtitle": "Carried past Sprint 26",
          "href": "/delivery-analysis?riskFocus=schedule",
          "tone": "success",
          "glyph": "\u25f7"
        },
        {
          "id": "ai",
          "title": "AI code risk at 8%",
          "subtitle": "Watch hotspots",
          "href": "/code-analysis",
          "tone": "success",
          "glyph": "</>"
        },
        {
          "id": "compliance",
          "title": "2 compliance findings",
          "subtitle": "Mock \u2014 not in Jira export",
          "href": "/governance",
          "tone": "success",
          "glyph": "\u2662"
        }
      ],
      "pillars": [
        {
          "id": "delivery",
          "name": "Delivery",
          "score": 100,
          "delta": 8,
          "footnote": "74 / 74 completed",
          "progress": 100,
          "tone": "steady",
          "glyph": "\u2691",
          "href": "/delivery-analysis"
        },
        {
          "id": "code",
          "name": "Code",
          "score": 85,
          "delta": 0,
          "footnote": "0 blocked issues",
          "progress": 85,
          "tone": "steady",
          "glyph": "</>",
          "href": "/code-analysis"
        },
        {
          "id": "qa",
          "name": "QA",
          "score": 72,
          "delta": 0,
          "footnote": "73 open bugs",
          "progress": 72,
          "tone": "steady",
          "glyph": "\u2697",
          "href": "/qa"
        },
        {
          "id": "compliance",
          "name": "Compliance",
          "score": 81,
          "delta": 0,
          "footnote": "2 open findings",
          "progress": 81,
          "tone": "steady",
          "glyph": "\u2662",
          "href": "/governance"
        }
      ],
      "attention_count": 0,
      "attention_message": "Sprint 26 delivery signals look manageable \u2014 keep owners current."
    },
    "APEX:26": {
      "score": 100,
      "band": "Strong",
      "caption": "Sprint 26 closed near plan",
      "completion": 100,
      "done": 25,
      "total": 25,
      "blocked": 0,
      "spillover": 0,
      "ai": 5,
      "comp": 1,
      "bugs": 11,
      "takeaways": [
        {
          "id": "blocked",
          "title": "0 items blocked",
          "subtitle": "Down from last sprint",
          "href": "/delivery-analysis?riskFocus=blockers",
          "tone": "success",
          "glyph": "\u2197"
        },
        {
          "id": "at-risk",
          "title": "0 items at risk",
          "subtitle": "Carried past Sprint 26",
          "href": "/delivery-analysis?riskFocus=schedule",
          "tone": "success",
          "glyph": "\u25f7"
        },
        {
          "id": "ai",
          "title": "AI code risk at 5%",
          "subtitle": "No high-risk areas",
          "href": "/code-analysis",
          "tone": "success",
          "glyph": "</>"
        },
        {
          "id": "compliance",
          "title": "1 compliance finding",
          "subtitle": "Mock \u2014 not in Jira export",
          "href": "/governance",
          "tone": "success",
          "glyph": "\u2662"
        }
      ],
      "pillars": [
        {
          "id": "delivery",
          "name": "Delivery",
          "score": 100,
          "delta": 8,
          "footnote": "25 / 25 completed",
          "progress": 100,
          "tone": "steady",
          "glyph": "\u2691",
          "href": "/delivery-analysis"
        },
        {
          "id": "code",
          "name": "Code",
          "score": 85,
          "delta": 3,
          "footnote": "0 blocked issues",
          "progress": 85,
          "tone": "steady",
          "glyph": "</>",
          "href": "/code-analysis"
        },
        {
          "id": "qa",
          "name": "QA",
          "score": 87,
          "delta": 0,
          "footnote": "11 open bugs",
          "progress": 87,
          "tone": "steady",
          "glyph": "\u2697",
          "href": "/qa"
        },
        {
          "id": "compliance",
          "name": "Compliance",
          "score": 88,
          "delta": 0,
          "footnote": "1 open finding",
          "progress": 88,
          "tone": "steady",
          "glyph": "\u2662",
          "href": "/governance"
        }
      ],
      "attention_count": 0,
      "attention_message": "Sprint 26 delivery signals look manageable \u2014 keep owners current."
    },
    "DARK:26": {
      "score": 88,
      "band": "Strong",
      "caption": "Sprint 26 closed with carry-over",
      "completion": 89,
      "done": 17,
      "total": 19,
      "blocked": 0,
      "spillover": 2,
      "ai": 4,
      "comp": 1,
      "bugs": 19,
      "takeaways": [
        {
          "id": "blocked",
          "title": "0 items blocked",
          "subtitle": "Flat vs last sprint",
          "href": "/delivery-analysis?riskFocus=blockers",
          "tone": "success",
          "glyph": "\u2197"
        },
        {
          "id": "at-risk",
          "title": "2 items at risk",
          "subtitle": "Carried past Sprint 26",
          "href": "/delivery-analysis?riskFocus=schedule",
          "tone": "info",
          "glyph": "\u25f7"
        },
        {
          "id": "ai",
          "title": "AI code risk at 4%",
          "subtitle": "No high-risk areas",
          "href": "/code-analysis",
          "tone": "success",
          "glyph": "</>"
        },
        {
          "id": "compliance",
          "title": "1 compliance finding",
          "subtitle": "Mock \u2014 not in Jira export",
          "href": "/governance",
          "tone": "success",
          "glyph": "\u2662"
        }
      ],
      "pillars": [
        {
          "id": "delivery",
          "name": "Delivery",
          "score": 89,
          "delta": -5,
          "footnote": "17 / 19 completed",
          "progress": 89,
          "tone": "steady",
          "glyph": "\u2691",
          "href": "/delivery-analysis"
        },
        {
          "id": "code",
          "name": "Code",
          "score": 85,
          "delta": 0,
          "footnote": "0 blocked issues",
          "progress": 85,
          "tone": "steady",
          "glyph": "</>",
          "href": "/code-analysis"
        },
        {
          "id": "qa",
          "name": "QA",
          "score": 85,
          "delta": 0,
          "footnote": "19 open bugs",
          "progress": 85,
          "tone": "steady",
          "glyph": "\u2697",
          "href": "/qa"
        },
        {
          "id": "compliance",
          "name": "Compliance",
          "score": 88,
          "delta": 0,
          "footnote": "1 open finding",
          "progress": 88,
          "tone": "steady",
          "glyph": "\u2662",
          "href": "/governance"
        }
      ],
      "attention_count": 1,
      "attention_message": "Sprint 26 delivery signals look manageable \u2014 keep owners current."
    },
    "MOBILE:26": {
      "score": 5,
      "band": "At risk",
      "caption": "Sprint 26 closed behind plan",
      "completion": 7,
      "done": 1,
      "total": 14,
      "blocked": 1,
      "spillover": 13,
      "ai": 4,
      "comp": 1,
      "bugs": 6,
      "takeaways": [
        {
          "id": "blocked",
          "title": "1 item blocked",
          "subtitle": "Down from last sprint",
          "href": "/delivery-analysis?riskFocus=blockers",
          "tone": "success",
          "glyph": "\u2197"
        },
        {
          "id": "at-risk",
          "title": "13 items at risk",
          "subtitle": "Carried past Sprint 26",
          "href": "/delivery-analysis?riskFocus=schedule",
          "tone": "warning",
          "glyph": "\u25f7",
          "needsAction": true
        },
        {
          "id": "ai",
          "title": "AI code risk at 4%",
          "subtitle": "No high-risk areas",
          "href": "/code-analysis",
          "tone": "success",
          "glyph": "</>"
        },
        {
          "id": "compliance",
          "title": "1 compliance finding",
          "subtitle": "Mock \u2014 not in Jira export",
          "href": "/governance",
          "tone": "success",
          "glyph": "\u2662"
        }
      ],
      "pillars": [
        {
          "id": "delivery",
          "name": "Delivery",
          "score": 7,
          "delta": -10,
          "footnote": "1 / 14 completed",
          "progress": 7,
          "tone": "danger",
          "glyph": "\u2691",
          "href": "/delivery-analysis"
        },
        {
          "id": "code",
          "name": "Code",
          "score": 82,
          "delta": 4,
          "footnote": "1 blocked issue",
          "progress": 82,
          "tone": "steady",
          "glyph": "</>",
          "href": "/code-analysis"
        },
        {
          "id": "qa",
          "name": "QA",
          "score": 88,
          "delta": 0,
          "footnote": "6 open bugs",
          "progress": 88,
          "tone": "steady",
          "glyph": "\u2697",
          "href": "/qa"
        },
        {
          "id": "compliance",
          "name": "Compliance",
          "score": 88,
          "delta": 0,
          "footnote": "1 open finding",
          "progress": 88,
          "tone": "steady",
          "glyph": "\u2662",
          "href": "/governance"
        }
      ],
      "attention_count": 2,
      "attention_message": "13 items look likely to spill \u2014 review scope before close."
    }
  },
  "notes": {
    "jiraSource": "/Users/musthafa/Downloads/tbt.csv",
    "scope": "Latest sprint; Story/Bug/Feature/Epic only (Sub-tasks excluded)",
    "mockKept": [
      "aiRisk",
      "compliance",
      "commits",
      "prs",
      "deployments",
      "leadership"
    ],
    "derived": [
      "completion",
      "blocked",
      "spillover",
      "burndown",
      "jiraHeatmap",
      "trend",
      "qaOpenBugs",
      "confidenceScore"
    ]
  }
} as const;

export type TptOverviewDerived = typeof TPT_OVERVIEW_DERIVED;
