import type { OverviewDashboardModel } from "@/lib/overview/types";

/** Pixel-target fixture matching ~/Downloads/new-design (Connexus Overview). */
export function getOverviewFixture(
  overrides?: Partial<Pick<OverviewDashboardModel, "greetingName" | "teamKey">>,
): OverviewDashboardModel {
  return {
    greetingName: overrides?.greetingName ?? "Krishna",
    sprint: {
      id: "37",
      name: "Sprint 37",
      startLabel: "Aug 10",
      endLabel: "Aug 24",
      rangeLabel: "Aug 10 – Aug 24, 2026",
    },
    teamKey: overrides?.teamKey ?? null,
    teams: [
      { key: "WEB", name: "Connexus Web" },
      { key: "MOB", name: "Mobile App" },
      { key: "DATA", name: "Data Platform" },
      { key: "INFRA", name: "Infrastructure" },
    ],
    deliveryConfidence: {
      score: 48,
      band: "Caution",
      caption: "Sprint 37 is at risk of delay",
      metrics: [
        {
          id: "completion",
          label: "Sprint completion",
          value: "59%",
          progress: 59,
          annotation: "69 / 117",
          icon: "flag",
        },
        {
          id: "blocked",
          label: "Items blocked",
          value: 31,
          progress: 31,
          icon: "circle-x",
        },
        {
          id: "spillover",
          label: "Items spilling over",
          value: 16,
          progress: 16,
          icon: "trend-up",
        },
        {
          id: "ai-risk",
          label: "AI code risk",
          value: "6%",
          progress: 6,
          icon: "x",
        },
      ],
    },
    keyTakeaways: [
      {
        id: "blocked",
        title: "31 items blocked",
        subtitle: "+12 from last sprint",
        href: "/delivery-analysis",
        tone: "danger",
        glyph: "↗",
        needsAction: true,
      },
      {
        id: "at-risk",
        title: "16 items at risk",
        subtitle: "Likely to spill over",
        href: "/qa",
        tone: "warning",
        glyph: "◷",
        needsAction: true,
      },
      {
        id: "ai",
        title: "AI code risk at 6%",
        subtitle: "No high-risk areas",
        href: "/code-analysis",
        tone: "success",
        glyph: "</>",
      },
      {
        id: "compliance",
        title: "4 compliance findings",
        subtitle: "2 resolved this week",
        href: "/governance",
        tone: "success",
        glyph: "♢",
      },
    ],
    pillars: [
      {
        id: "delivery",
        name: "Delivery",
        score: 59,
        delta: -12,
        footnote: "69 / 117 completed",
        progress: 59,
        tone: "warning",
        glyph: "⚑",
      },
      {
        id: "code",
        name: "Code",
        score: 66,
        delta: 8,
        footnote: "30 blocked issues",
        progress: 66,
        tone: "steady",
        glyph: "</>",
      },
      {
        id: "qa",
        name: "QA",
        score: 44,
        delta: -16,
        footnote: "223 open bugs",
        progress: 44,
        tone: "danger",
        glyph: "⚗",
      },
      {
        id: "compliance",
        name: "Compliance",
        score: 65,
        delta: 5,
        footnote: "4 open findings",
        progress: 65,
        tone: "steady",
        glyph: "♢",
      },
    ],
    deliveryTrend: {
      rangeLabel: "Last 6 weeks",
      target: 80,
      points: [
        { label: "Jul 13", value: 94 },
        { label: "Jul 16", value: 76 },
        { label: "Jul 20", value: 68 },
        { label: "Jul 23", value: 59 },
        { label: "Jul 27", value: 45 },
        { label: "Jul 30", value: 37 },
        { label: "Aug 3", value: 17 },
        { label: "Aug 10", value: 18 },
        { label: "Aug 17", value: 8 },
        { label: "Aug 24", value: 22 },
      ],
    },
    burndown: {
      completed: 69,
      total: 117,
      ideal: [
        { label: "Aug 10", value: 120 },
        { label: "Aug 13", value: 96 },
        { label: "Aug 16", value: 72 },
        { label: "Aug 19", value: 48 },
        { label: "Aug 22", value: 24 },
        { label: "Aug 24", value: 0 },
      ],
      actual: [
        { label: "Aug 10", value: 120 },
        { label: "Aug 13", value: 105 },
        { label: "Aug 16", value: 92 },
        { label: "Aug 19", value: 70 },
        { label: "Aug 22", value: 47 },
        { label: "Aug 24", value: 28 },
      ],
    },
    heatmap: {
      rangeLabel: "Last 2 weeks",
      dayLabels: ["Aug 10", "Aug 13", "Aug 16", "Aug 19", "Aug 22", "Aug 24"],
      rows: [
        {
          label: "Commits",
          cells: [0, 0, 0, 2, 0, 3, 0, 2, 0, 1, 2, 0, 3, 0, 1, 0],
        },
        {
          label: "PRs",
          cells: [1, 2, 3, 2, 0, 1, 3, 0, 2, 1, 0, 3, 2, 0, 1, 2],
        },
        {
          label: "Jira updates",
          cells: [2, 1, 0, 3, 2, 1, 0, 2, 3, 0, 1, 0, 2, 3, 0, 2],
        },
        {
          label: "Deployments",
          cells: [0, 1, 2, 0, 3, 2, 0, 1, 2, 0, 3, 1, 0, 2, 0, 3],
        },
      ],
    },
    attention: {
      count: 2,
      message:
        "30 blocked issues are in the evidence set — ask engineering for an owner and ETA.",
      href: "/delivery-analysis",
    },
    leadership: {
      count: 1,
      href: "/approvals",
    },
    lastSyncAt: new Date(Date.now() - 11 * 60 * 1000).toISOString(),
    empty: false,
  };
}
